# -*- coding: utf-8 -*-
"""Thai vocabulary deck: (Thai, romanization, English).

The first ~297 entries are hand-curated with romanization.
The rest are the most frequent words from the SEAlang/AUA Thai
corpus (Thai + English; romanization left blank).
Source: github.com/waf/anki-thai (resources/cards.sealang.json)
"""

VOCAB = [
    ('สวัสดี', 'sawatdii', 'Hello'),
    ('สวัสดีครับ', 'sawatdii khrap', 'Hello (male speaker)'),
    ('สวัสดีค่ะ', 'sawatdii kha', 'Hello (female speaker)'),
    ('ขอบคุณ', 'khopkhun', 'Thank you'),
    ('ขอบคุณมาก', 'khopkhun maak', 'Thank you very much'),
    ('ขอโทษ', 'khothot', 'Sorry / Excuse me'),
    ('ไม่เป็นไร', 'mai pen rai', "It's okay / You're welcome"),
    ('ยินดี', 'yindii', 'Glad / Pleased'),
    ('ลาก่อน', 'laa kon', 'Goodbye'),
    ('แล้วเจอกัน', 'laeo joe kan', 'See you later'),
    ('โชคดี', 'chok dii', 'Good luck'),
    ('สบายดีไหม', 'sabai dii mai', 'How are you?'),
    ('สบายดี', 'sabai dii', "I'm fine"),
    ('ยินดีที่ได้รู้จัก', 'yindii thii dai ruujak', 'Nice to meet you'),
    ('ใช่', 'chai', 'Yes'),
    ('ไม่ใช่', 'mai chai', 'No / Not so'),
    ('ไม่', 'mai', 'No / Not'),
    ('ได้', 'dai', 'Can / OK'),
    ('ไม่ได้', 'mai dai', 'Cannot'),
    ('มี', 'mii', 'Have / There is'),
    ('ไม่มี', 'mai mii', "Don't have"),
    ('ชอบ', 'chop', 'Like'),
    ('ไม่ชอบ', 'mai chop', "Don't like"),
    ('ต้องการ', 'tongkaan', 'Want / Need'),
    ('อยาก', 'yaak', 'Want to'),
    ('รู้', 'ruu', 'Know'),
    ('ไม่รู้', 'mai ruu', "Don't know"),
    ('เข้าใจ', 'khaojai', 'Understand'),
    ('ไม่เข้าใจ', 'mai khaojai', "Don't understand"),
    ('ผม', 'phom', 'I (male)'),
    ('ฉัน', 'chan', 'I (female/informal)'),
    ('คุณ', 'khun', 'You (polite)'),
    ('เรา', 'rao', 'We / I (casual)'),
    ('เขา', 'khao', 'He / She'),
    ('มัน', 'man', 'It'),
    ('พวกเขา', 'phuak khao', 'They'),
    ('นี่', 'nii', 'This'),
    ('นั่น', 'nan', 'That'),
    ('ที่นี่', 'thii nii', 'Here'),
    ('ที่นั่น', 'thii nan', 'There'),
    ('อะไร', 'arai', 'What'),
    ('ใคร', 'khrai', 'Who'),
    ('ที่ไหน', 'thii nai', 'Where'),
    ('เมื่อไหร่', 'muea rai', 'When'),
    ('ทำไม', 'thammai', 'Why'),
    ('อย่างไร', 'yang ngai', 'How'),
    ('เท่าไหร่', 'thao rai', 'How much'),
    ('กี่', 'kii', 'How many'),
    ('อันไหน', 'an nai', 'Which one'),
    ('ศูนย์', 'suun', 'Zero'),
    ('หนึ่ง', 'nueng', 'One'),
    ('สอง', 'song', 'Two'),
    ('สาม', 'saam', 'Three'),
    ('สี่', 'sii', 'Four'),
    ('ห้า', 'haa', 'Five'),
    ('หก', 'hok', 'Six'),
    ('เจ็ด', 'jet', 'Seven'),
    ('แปด', 'paet', 'Eight'),
    ('เก้า', 'kao', 'Nine'),
    ('สิบ', 'sip', 'Ten'),
    ('สิบเอ็ด', 'sip et', 'Eleven'),
    ('ยี่สิบ', 'yii sip', 'Twenty'),
    ('สามสิบ', 'saam sip', 'Thirty'),
    ('ร้อย', 'roi', 'Hundred'),
    ('พัน', 'phan', 'Thousand'),
    ('หมื่น', 'muen', 'Ten thousand'),
    ('แสน', 'saen', 'Hundred thousand'),
    ('ล้าน', 'laan', 'Million'),
    ('ครอบครัว', 'khropkhrua', 'Family'),
    ('พ่อ', 'pho', 'Father'),
    ('แม่', 'mae', 'Mother'),
    ('พี่', 'phii', 'Older sibling'),
    ('น้อง', 'nong', 'Younger sibling'),
    ('ลูก', 'luuk', 'Child (offspring)'),
    ('เด็ก', 'dek', 'Child / Kid'),
    ('ผู้ชาย', 'phuu chai', 'Man'),
    ('ผู้หญิง', 'phuu ying', 'Woman'),
    ('เพื่อน', 'phuean', 'Friend'),
    ('แฟน', 'faen', 'Boy/Girlfriend'),
    ('สามี', 'saamii', 'Husband'),
    ('ภรรยา', 'phanrayaa', 'Wife'),
    ('ปู่', 'puu', 'Grandfather (paternal)'),
    ('ย่า', 'yaa', 'Grandmother (paternal)'),
    ('ครู', 'khruu', 'Teacher'),
    ('นักเรียน', 'nakrian', 'Student'),
    ('หมอ', 'mo', 'Doctor'),
    ('ตำรวจ', 'tamruat', 'Police'),
    ('อาหาร', 'aahaan', 'Food'),
    ('ข้าว', 'khao', 'Rice / Meal'),
    ('น้ำ', 'nam', 'Water'),
    ('กาแฟ', 'kafae', 'Coffee'),
    ('ชา', 'chaa', 'Tea'),
    ('นม', 'nom', 'Milk'),
    ('เบียร์', 'bia', 'Beer'),
    ('ขนม', 'khanom', 'Snack / Dessert'),
    ('ผลไม้', 'phonlamai', 'Fruit'),
    ('เนื้อ', 'nuea', 'Meat / Beef'),
    ('หมู', 'muu', 'Pork'),
    ('ไก่', 'kai', 'Chicken'),
    ('ปลา', 'plaa', 'Fish'),
    ('กุ้ง', 'kung', 'Shrimp'),
    ('ไข่', 'khai', 'Egg'),
    ('ผัก', 'phak', 'Vegetable'),
    ('เผ็ด', 'phet', 'Spicy'),
    ('หวาน', 'waan', 'Sweet'),
    ('เค็ม', 'khem', 'Salty'),
    ('เปรี้ยว', 'priao', 'Sour'),
    ('อร่อย', 'aroi', 'Delicious'),
    ('หิว', 'hiw', 'Hungry'),
    ('อิ่ม', 'im', 'Full (satiated)'),
    ('กิน', 'kin', 'Eat'),
    ('ดื่ม', 'duem', 'Drink'),
    ('กล้วย', 'kluai', 'Banana'),
    ('ส้ม', 'som', 'Orange'),
    ('มะม่วง', 'mamuang', 'Mango'),
    ('แตงโม', 'taengmo', 'Watermelon'),
    ('สับปะรด', 'sapparot', 'Pineapple'),
    ('มะพร้าว', 'maphrao', 'Coconut'),
    ('องุ่น', 'angun', 'Grape'),
    ('แอปเปิ้ล', 'aeppoen', 'Apple'),
    ('สัตว์', 'sat', 'Animal'),
    ('แมว', 'maew', 'Cat'),
    ('หมา', 'maa', 'Dog'),
    ('นก', 'nok', 'Bird'),
    ('ช้าง', 'chang', 'Elephant'),
    ('ม้า', 'maa', 'Horse'),
    ('วัว', 'wua', 'Cow'),
    ('เสือ', 'suea', 'Tiger'),
    ('ลิง', 'ling', 'Monkey'),
    ('งู', 'nguu', 'Snake'),
    ('สี', 'sii', 'Color'),
    ('สีแดง', 'sii daeng', 'Red'),
    ('สีน้ำเงิน', 'sii nam ngoen', 'Blue'),
    ('สีเขียว', 'sii khiao', 'Green'),
    ('สีเหลือง', 'sii lueang', 'Yellow'),
    ('สีดำ', 'sii dam', 'Black'),
    ('สีขาว', 'sii khao', 'White'),
    ('สีชมพู', 'sii chomphuu', 'Pink'),
    ('สีส้ม', 'sii som', 'Orange (color)'),
    ('สีม่วง', 'sii muang', 'Purple'),
    ('สีน้ำตาล', 'sii nam taan', 'Brown'),
    ('เวลา', 'welaa', 'Time'),
    ('วัน', 'wan', 'Day'),
    ('วันนี้', 'wan nii', 'Today'),
    ('เมื่อวาน', 'muea waan', 'Yesterday'),
    ('พรุ่งนี้', 'phrung nii', 'Tomorrow'),
    ('เช้า', 'chao', 'Morning'),
    ('เที่ยง', 'thiang', 'Noon'),
    ('บ่าย', 'baai', 'Afternoon'),
    ('เย็น', 'yen', 'Evening'),
    ('กลางคืน', 'klang khuen', 'Night'),
    ('ชั่วโมง', 'chua mong', 'Hour'),
    ('นาที', 'naathii', 'Minute'),
    ('สัปดาห์', 'sapdaa', 'Week'),
    ('เดือน', 'duean', 'Month'),
    ('ปี', 'pii', 'Year'),
    ('วันจันทร์', 'wan chan', 'Monday'),
    ('วันอังคาร', 'wan angkhaan', 'Tuesday'),
    ('วันพุธ', 'wan phut', 'Wednesday'),
    ('วันพฤหัส', 'wan pharuehat', 'Thursday'),
    ('วันศุกร์', 'wan suk', 'Friday'),
    ('วันเสาร์', 'wan sao', 'Saturday'),
    ('วันอาทิตย์', 'wan aathit', 'Sunday'),
    ('บ้าน', 'baan', 'Home / House'),
    ('โรงเรียน', 'rongrian', 'School'),
    ('โรงพยาบาล', 'rongphayabaan', 'Hospital'),
    ('ตลาด', 'talaat', 'Market'),
    ('ร้าน', 'raan', 'Shop'),
    ('ร้านอาหาร', 'raan aahaan', 'Restaurant'),
    ('ห้องน้ำ', 'hong nam', 'Bathroom'),
    ('ธนาคาร', 'thanakhaan', 'Bank'),
    ('สนามบิน', 'sanaam bin', 'Airport'),
    ('โรงแรม', 'rongraem', 'Hotel'),
    ('สถานี', 'sathaanii', 'Station'),
    ('วัด', 'wat', 'Temple'),
    ('เมือง', 'mueang', 'City / Town'),
    ('ประเทศ', 'prathet', 'Country'),
    ('ถนน', 'thanon', 'Road / Street'),
    ('รถ', 'rot', 'Car / Vehicle'),
    ('รถเมล์', 'rot me', 'Bus'),
    ('รถไฟ', 'rot fai', 'Train'),
    ('รถไฟฟ้า', 'rot fai faa', 'Skytrain (BTS)'),
    ('แท็กซี่', 'thaeksii', 'Taxi'),
    ('มอเตอร์ไซค์', 'motoesai', 'Motorbike'),
    ('เครื่องบิน', 'khrueang bin', 'Airplane'),
    ('เรือ', 'ruea', 'Boat'),
    ('จักรยาน', 'jakkrayaan', 'Bicycle'),
    ('ไป', 'pai', 'Go'),
    ('มา', 'maa', 'Come'),
    ('ตั๋ว', 'tua', 'Ticket'),
    ('ซ้าย', 'sai', 'Left'),
    ('ขวา', 'khwaa', 'Right'),
    ('ตรง', 'trong', 'Straight'),
    ('ตรงไป', 'trong pai', 'Go straight'),
    ('หยุด', 'yut', 'Stop'),
    ('ใกล้', 'klai', 'Near'),
    ('ไกล', 'klai', 'Far'),
    ('บน', 'bon', 'On / Above'),
    ('ล่าง', 'laang', 'Below'),
    ('ใน', 'nai', 'In / Inside'),
    ('นอก', 'nok', 'Outside'),
    ('ข้าง', 'khaang', 'Beside'),
    ('ทำ', 'tham', 'Do / Make'),
    ('พูด', 'phuut', 'Speak / Say'),
    ('ฟัง', 'fang', 'Listen'),
    ('อ่าน', 'aan', 'Read'),
    ('เขียน', 'khian', 'Write'),
    ('ดู', 'duu', 'Watch / Look'),
    ('เห็น', 'hen', 'See'),
    ('เดิน', 'doen', 'Walk'),
    ('วิ่ง', 'wing', 'Run'),
    ('นั่ง', 'nang', 'Sit'),
    ('ยืน', 'yuen', 'Stand'),
    ('นอน', 'non', 'Sleep / Lie down'),
    ('ตื่น', 'tuen', 'Wake up'),
    ('ทำงาน', 'tham ngaan', 'Work'),
    ('เรียน', 'rian', 'Study'),
    ('เล่น', 'len', 'Play'),
    ('ซื้อ', 'sue', 'Buy'),
    ('ขาย', 'khaai', 'Sell'),
    ('จ่าย', 'jaai', 'Pay'),
    ('ให้', 'hai', 'Give'),
    ('เอา', 'ao', 'Take / Want'),
    ('รอ', 'ro', 'Wait'),
    ('ช่วย', 'chuai', 'Help'),
    ('รัก', 'rak', 'Love'),
    ('คิด', 'khit', 'Think'),
    ('จำ', 'jam', 'Remember'),
    ('ลืม', 'luem', 'Forget'),
    ('เปิด', 'poet', 'Open / Turn on'),
    ('ปิด', 'pit', 'Close / Turn off'),
    ('ดี', 'dii', 'Good'),
    ('ไม่ดี', 'mai dii', 'Bad'),
    ('ใหญ่', 'yai', 'Big'),
    ('เล็ก', 'lek', 'Small'),
    ('ยาว', 'yaao', 'Long'),
    ('สั้น', 'san', 'Short'),
    ('ร้อน', 'ron', 'Hot'),
    ('หนาว', 'naao', 'Cold (weather)'),
    ('ใหม่', 'mai', 'New'),
    ('เก่า', 'kao', 'Old (thing)'),
    ('แพง', 'phaeng', 'Expensive'),
    ('ถูก', 'thuuk', 'Cheap / Correct'),
    ('สวย', 'suay', 'Beautiful'),
    ('น่ารัก', 'narak', 'Cute'),
    ('เร็ว', 'reo', 'Fast'),
    ('ช้า', 'chaa', 'Slow'),
    ('ง่าย', 'ngaai', 'Easy'),
    ('ยาก', 'yaak', 'Difficult'),
    ('มาก', 'maak', 'Very / A lot'),
    ('นิดหน่อย', 'nit noi', 'A little'),
    ('ดีใจ', 'dii jai', 'Happy / Glad'),
    ('เสียใจ', 'sia jai', 'Sad'),
    ('โกรธ', 'krot', 'Angry'),
    ('เหนื่อย', 'nueay', 'Tired'),
    ('ง่วง', 'nguang', 'Sleepy'),
    ('สนุก', 'sanuk', 'Fun'),
    ('เบื่อ', 'buea', 'Bored'),
    ('กลัว', 'klua', 'Afraid'),
    ('สบาย', 'sabai', 'Comfortable / Well'),
    ('หัว', 'hua', 'Head'),
    ('ตา', 'taa', 'Eye'),
    ('หู', 'huu', 'Ear'),
    ('จมูก', 'jamuuk', 'Nose'),
    ('ปาก', 'paak', 'Mouth'),
    ('มือ', 'mue', 'Hand'),
    ('เท้า', 'thao', 'Foot'),
    ('ท้อง', 'thong', 'Stomach'),
    ('ใจ', 'jai', 'Heart / Mind'),
    ('อากาศ', 'aakaat', 'Weather / Air'),
    ('ฝน', 'fon', 'Rain'),
    ('แดด', 'daet', 'Sunshine'),
    ('ลม', 'lom', 'Wind'),
    ('เมฆ', 'mek', 'Cloud'),
    ('ฟ้า', 'faa', 'Sky'),
    ('ทะเล', 'thale', 'Sea'),
    ('ภูเขา', 'phuukhao', 'Mountain'),
    ('ต้นไม้', 'ton mai', 'Tree'),
    ('ดอกไม้', 'dok mai', 'Flower'),
    ('เงิน', 'ngoen', 'Money'),
    ('บาท', 'baat', 'Baht'),
    ('ราคา', 'raakhaa', 'Price'),
    ('ลดราคา', 'lot raakhaa', 'Discount'),
    ('เท่าไหร่ครับ', 'thao rai khrap', 'How much? (male)'),
    ('ช่วยด้วย', 'chuai duai', 'Help!'),
    ('พูดอีกครั้ง', 'phuut iik khrang', 'Say it again'),
    ('พูดช้าๆ', 'phuut chaa chaa', 'Please speak slowly'),
    ('ไม่เป็นไรครับ', 'mai pen rai khrap', 'No problem (male)'),
    ('เข้าใจแล้ว', 'khaojai laeo', 'I understand now'),
    ('อร่อยมาก', 'aroi maak', 'Very delicious'),
    ('เก่งมาก', 'keng maak', 'Well done!'),
    ('สู้ๆ', 'suu suu', 'You can do it!'),
    ('แพงไป', 'phaeng pai', 'Too expensive'),
    ('ขอเมนู', 'kho menuu', 'May I have the menu'),
    ('เช็คบิล', 'chek bin', 'Check please'),
    ('ไปไหน', 'pai nai', 'Where are you going?'),
    ('กินข้าวหรือยัง', 'kin khao rue yang', 'Have you eaten yet?'),
    ('หน้า', 'na', 'Face'),
    ('เป็น', 'pen', 'To be someone or something'),
    ('คน', 'khon', 'Person, people'),
    ('ที่', 'thi', 'At'),
    ('อยู่', 'yu', 'To be some place'),
    ('แล้ว', 'laeo', 'And then, subsequently'),
    ('นี้', 'ni', 'This (adjective)'),
    ('กับ', 'kap', 'With, and'),
    ('ผู้', 'phu', 'Person (rarely used alone)'),
    ('งาน', 'ngan', 'Work, party, ceremony'),
    ('จะ', 'cha', 'Will'),
    ('ใช้', 'chai', 'To use'),
    ('ไทย', 'thai', 'Thai'),
    ('ว่า', 'wa', 'A quotation signal'),
    ('และ', 'lae', 'And'),
    ('ด้วย', 'duai', 'Also, too'),
    ('อ๋อ', 'o', 'Oh, I see'),
    ('ของ', 'khong', 'Thing'),
    ('เข้า', 'khao', 'To enter, to go or come in'),
    ('จาก', 'chak', 'From, to separate from'),
    ('โดย', 'doi', 'By means of, with, by'),
    ('ความ', 'khwam', 'Essence, stuff, -ness,-ity'),
    ('หรือ', 'rue', 'or not'),
    ('ส', 'sa', 'sor - sya'),
    ('ค', 'kho', 'khor - khwaaj'),
    ('น', 'na', 'nor -nuu'),
    ('ร', 'ra', 'ror - rya'),
    ('ก', 'ko', 'kor kai'),
    ('ต', 'ta', 'tor - tao'),
    ('อ', 'a', 'or - ang'),
    ('อึ', 'ue', 'poop (cutesy)'),
    ('ครับ', 'khrap', 'Masculine polite particle, confirmative'),
    ('ค่ะ', 'kha', 'Feminine polite particle, confirmative'),
    ('จ้ะ', 'cha', 'Polite particle, confirmative'),
    ('ถึง', 'thueng', 'Reach'),
    ('ขอ', 'kho', 'To ask for'),
    ('สูง', 'sung', 'tall'),
    ('นั้น', 'nan', 'That, the one mentioned'),
    ('ทาง', 'thang', 'Way, path'),
    ('หลัง', 'lang', 'The back'),
    ('กว่า', 'kwa', 'More (than), -er (than)'),
    ('กัน', 'kan', 'The other, each other, mutually, together, as a group'),
    ('นะ', 'na', "A particle softening a request (like 'ok?'), requesting..."),
    ('อีก', 'ik', 'Another, one more, more'),
    ('เกิด', 'koet', 'To be born'),
    ('ก่อน', 'kon', 'Before, first'),
    ('พบ', 'phop', 'To see, meet, find'),
    ('กลับ', 'klap', 'To return'),
    ('หา', 'ha', 'To look for'),
    ('ทราบ', 'sap', 'To know (information)'),
    ('โทรศัพท์', 'thorasap', 'Telephone, to telephone'),
    ('ภาษา', 'phasa', 'Language'),
    ('ก็', 'ko', 'Also, too'),
    ('แต่', 'tae', 'But'),
    ('เท่านั้น', 'thaonan', 'Only'),
    ('บ้าง', 'bang', 'Some'),
    ('ส่ง', 'song', 'To send'),
    ('บอก', 'bok', 'To tell'),
    ('ชื่อ', 'chue', 'Name, to be named'),
    ('ถ้า', 'tha', 'If'),
    ('ถาม', 'tham', 'To ask'),
    ('ต้อง', 'tong', 'To have to, must'),
    ('อย่าง', 'yang', 'Kind, sort, variety'),
    ('เดียว', 'diao', 'Single, only one, one and the same'),
    ('คำ', 'kham', 'Word'),
    ('ยัง', 'yang', 'Still, yet'),
    ('ทัก', 'thak', 'To greet, say hello to'),
    ('ตาม', 'tam', 'To follow'),
    ('เพราะ', 'phro', 'To sound good'),
    ('เมื่อ', 'muea', 'When'),
    ('ชาติ', 'chati', 'Nationality'),
    ('ทั้ง', 'thang', 'All of'),
    ('ทั้งหมด', 'thangmot', 'Altogether'),
    ('เอง', 'eng', 'Self, by oneself, just (after demonstratives)'),
    ('หลาย', 'lai', 'Several'),
    ('รับ', 'rap', 'To receive, pick up someone'),
    ('เลย', 'loei', 'To be beyond'),
    ('ลง', 'long', 'To descend, go or come down, diminish'),
    ('ตัว', 'tua', 'Body. Classifier for animals, chairs, tables, and artic...'),
    ('ขึ้น', 'khuen', 'To ascend, go or come up, increase'),
    ('ตั้ง', 'tang', 'To set up, erect, situate'),
    ('ออก', 'ok', 'To exit, to go or come out, to pay out'),
    ('กำลัง', 'kamlang', 'In the process of'),
    ('งั้น', 'ngan', 'Short for ถ้ายังงั้น'),
    ('คับ', 'khap', 'Tight'),
    ('ศึกษา', 'sueksa', 'To educate'),
    ('บาง', 'bang', 'thin'),
    ('ผ่าน', 'phan', 'To pass a fixed object'),
    ('พฤศจิกายน', 'phritchikain', 'November'),
    ('ละ', 'la', 'Per'),
    ('นาย', 'nai', 'Mr., master, boss'),
    ('สุด', 'sut', 'The end, extreme, utmost'),
    ('ที่สุด', 'thisut', 'The most, extremely'),
    ('ทุก', 'thuk', 'Every'),
    ('เคย', 'khoei', 'Having experienced'),
    ('เรื่อง', 'rueang', 'A story, a matter, classifier for stories or happenings'),
    ('อาจ', 'at', 'May, might, maybe'),
    ('คง', 'khong', 'Most likely, sure to, bound to'),
    ('ควร', 'khuan', 'Should, ought to'),
    ('อื่น', 'uen', 'Other'),
    ('จึง', 'chueng', 'So, therefore, consequently'),
    ('ค่า', 'kha', 'Expenses, fee, cost, value'),
    ('จริง', 'ching', 'true'),
    ('ติด', 'tit', 'attached to'),
    ('เก็บ', 'kep', 'To collect, keep, store'),
    ('ขนาด', 'khanat', 'Size, magnitude'),
    ('ไว้', 'wai', 'For future use or reference'),
    ('พิมพ์', 'phim', 'To print'),
    ('จัด', 'chat', 'Strong, intense, extreme'),
    ('ส่วน', 'suan', 'A part'),
    ('ซึ่ง', 'sueng', 'Relative pronoun (that, which)'),
    ('ตั้งแต่', 'tangtae', 'Since'),
    ('น้อย', 'noi', 'small in number or amount'),
    ('เพิ่ม', 'phoem', 'To increase'),
    ('สำหรับ', 'samrap', 'For doing something, for someone, as for'),
    ('ทั่ว', 'thua', 'all over, throughout'),
    ('ติดต่อ', 'titto', 'To contact, get in touch with'),
    ('ต่อ', 'to', 'To join on to, continue oil, connect'),
    ('ต่างๆ', 'tango', 'Various'),
    ('แนะนำ', 'nanam', 'To suggest, advise, introduce'),
    ('ภายใน', 'phainai', 'Within'),
    ('แรก', 'raek', 'first'),
    ('จังหวัด', 'changwat', 'Province'),
    ('คือ', 'khue', 'To be as follows or defined, namely'),
    ('นัก', 'nak', 'So, very'),
    ('ธุรกิจ', 'thurakit', 'Business'),
    ('แบบ', 'baep', 'Type, style'),
    ('น่า', 'na', 'Good for..., interesting to..'),
    ('ประกาศ', 'prakat', 'To announce'),
    ('กรุณา', 'karuna', "kind, merciful. 'Please.'"),
    ('สร้าง', 'sang', 'To build'),
    ('เลือก', 'lueak', 'To choose'),
    ('รวม', 'ruam', 'To combine, include'),
    ('แจ้ง', 'chaeng', 'To make known, inform, report'),
    ('ครั้ง', 'khrang', 'A time, occasion'),
    ('แห่ง', 'haeng', 'Place, classifier of places'),
    ('เพลง', 'phleng', 'A song'),
    ('สำคัญ', 'samkhan', 'important'),
    ('ประจำ', 'pracham', 'regular, normal'),
    ('ระหว่าง', 'rawang', 'between'),
    ('สินค้า', 'sinkha', 'goods'),
    ('ศ', 'ta', 'sor - sala'),
    ('ห', 'ho', 'hor - hiip'),
    ('สมัคร', 'samakkhon', 'to apply'),
    ('ง', 'ng', '..ngor - nguu'),
    ('ช', 'cha', 'chor - chang'),
    ('ซ', 'so', 'sor - soo'),
    ('ญ', 'ya', 'jor - phuu jing'),
    ('ณ', 'na', 'nor - naen'),
    ('ท', 'tha', 'thor - tha-haan'),
    ('ธ', 'tha', 'thor - thong'),
    ('พ', 'pho', 'phor - phaan'),
    ('ฟ', 'p', 'for -fan'),
    ('ม', 'm', 'mor - maa'),
    ('ย', 'ya', 'jor - jak'),
    ('ล', 'la', 'lor - ling'),
    ('ว', 'a', 'wor - wa-an'),
    ('จ', 'cha', 'cor - caan'),
    ('ด', 'ta', 'dor - dek'),
    ('บ', 'bo', 'bor- baj maj'),
    ('ป', 'pa', 'por - plaa'),
    ('แสดง', 'sadang', 'to perform'),
    ('รูป', 'rup', 'picture'),
    ('โลก', 'lok', 'Earth'),
    ('คิ้ว', 'khio', 'eyebrow'),
    ('ผล', 'phon', 'result'),
    ('โฆษณา', 'khosana', 'advertisement'),
    ('ข่าว', 'khao', 'news'),
    ('คอม', 'khom', 'computer (colloquial)'),
    ('การศึกษา', 'kansueksa', 'education'),
    ('ลบ', 'lop', 'to erase'),
    ('ตอบ', 'top', 'to answer'),
    ('หลัก', 'lak', 'digit'),
    ('ประเทศไทย', 'prathet thai', 'Thailand'),
    ('กีฬา', 'kila', 'sport'),
    ('ต่อไป', 'topai', 'next'),
    ('วันที่', 'wanthi', 'date'),
    ('แก้ไข', 'kaekhai', 'to revise'),
    ('ค้นหา', 'khonha', 'to search'),
    ('นำ', 'nam', 'to lead'),
    ('เว็บ', 'wep', 'webpage (colloquial)'),
    ('กระทู้', 'krathu', 'thread'),
    ('สามารถ', 'samat', 'capable'),
    ('ข้อมูล', 'khomun', 'data'),
    ('ระดับ', 'radap', 'grade, n. (quality)'),
    ('ภาพ', 'phap', 'image, n. (picture)'),
    ('บุคคล', 'bukkhon', 'individual, n'),
    ('จำกัด', 'chamkat', 'restrict'),
    ('คะ', 'kha', 'Feminine polite particle'),
    ('ไหม', 'haimai', 'A question particle'),
    ('นา', 'na', 'Rice field'),
    ('ไร', 'rai', 'Short form of อะไร (what)'),
    ('ตัด', 'tat', 'To cut'),
    ('ไหน', 'nai', 'Where? Which?'),
    ('ล่ะ', 'la', 'A particle used to direct a previous question to a new...'),
    ('เอ็ด', 'et', 'One (used in combinations like 21, 31)'),
    ('รู้จัก', 'ruchak', 'To know a person, place, or thing, to be acquainted with'),
    ('แยก', 'yaek', 'To fork, separate'),
    ('ชาย', 'chai', 'Male (people only)'),
    ('หญิง', 'ying', 'Female (people only)'),
    ('ใส่', 'sai', 'To put in or on'),
    ('ที', 'thi', 'A time'),
    ('อังกฤษ', 'angkrit', 'England, English'),
    ('วิทยุ', 'witthayu', 'Radio, wireless'),
    ('เชิญ', 'choen', 'To invite. Go ahead. Please do. Help yourself'),
    ('สั่ง', 'sang', 'To order, to leave a message'),
    ('ทิ้ง', 'thing', 'To throw away'),
    ('เลขที่', 'lekthi', 'A number used as a designation'),
    ('จับ', 'chap', 'To catch, grab'),
    ('เบอร์', 'boe', 'Number'),
    ('จีน', 'chin', 'Chinese'),
    ('หนังสือ', 'nangsue', 'Book'),
    ('หน่อย', 'noi', 'A little'),
    ('เรียก', 'riak', 'To call'),
    ('แดง', 'daeng', 'Red'),
    ('ขาว', 'khao', 'White'),
    ('สาย', 'sai', 'Late morning'),
    ('ตอน', 'ton', 'A section or period'),
    ('ไฟ', 'fai', 'Fire, light'),
    ('ดำ', 'dam', 'Black'),
    ('ไม้', 'mai', 'Wood; a stick'),
    ('สาว', 'sao', 'Young woman, unmarried woman'),
    ('ว่าง', 'wang', 'unoccupied, free'),
    ('เตือน', 'tuean', 'To remind, warn'),
    ('เที่ยว', 'thiao', 'To go from place to place'),
    ('แล้วก็', 'laeoko', 'And, and then'),
    ('เหมือนกัน', 'mueankan', 'Likewise'),
    ('เสร็จ', 'set', 'To finish, be finished'),
    ('พอ', 'pho', 'Enough'),
    ('กลาง', 'klang', 'Center, middle, in the middle of'),
    ('แน่', 'nae', 'To be certain'),
    ('บ่อย', 'boi', 'Often'),
    ('รถยนต์', 'rothon', 'Automobile'),
    ('นาน', 'nan', 'long (in time)'),
    ('แก้', 'kae', 'To repair, make right, to correct'),
    ('เสีย', 'sia', 'spoiled, out of order, to spend'),
    ('อา', 'a', "Father's younger sibling (aunt, uncle)"),
    ('อาทิตย์', 'athit', 'Week'),
    ('รายการ', 'raikan', 'A list of items'),
    ('ยา', 'ya', 'Medicine, tobacco'),
    ('ดาว', 'dao', 'Star'),
    ('ปกติ', 'pokti', 'Normally, ordinarily'),
    ('เหมาะสม', 'mosom', 'appropriate'),
    ('เยี่ยม', 'yiam', 'To visit'),
    ('กรุงเทพฯ', 'krungtheppaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'Bangkok'),
    ('หนัก', 'nak', 'heavy'),
    ('เสมอ', 'samoe', 'Always'),
    ('อย่า', 'aya', "Don't (the negative imperative)"),
    ('คู่', 'khu', 'A pair (classifier)'),
    ('คืน', 'khuen', 'Night'),
    ('หนัง', 'nang', 'Cinema, movie'),
    ('หมด', 'mot', 'all gone'),
    ('พา', 'pha', 'To take someone somewhere'),
    ('รักษา', 'raksa', 'To take care of, treat'),
    ('ซิ', 'si', 'A particle used to request or urge an action'),
    ('ขา', 'kha', 'Leg'),
    ('หลังจาก', 'langchak', 'After'),
    ('ตำแหน่ง', 'tamnaeng', 'Rank, position'),
    ('กันยายน', 'kanyayon', 'September'),
    ('สิงหาคม', 'singhakhom', 'August'),
    ('สวน', 'suan', 'A garden or orchard'),
    ('เธอ', 'thoe', 'You (to intimates or inferiors)'),
    ('ตุลาคม', 'tulakhom', 'October'),
    ('โรค', 'rok', 'Disease'),
    ('ถู', 'thu', 'To scrub'),
    ('แก่', 'kae', 'old (opposite of young, not the opposite of new)'),
    ('ลด', 'lot', 'To reduce in price or weight'),
    ('ตก', 'tok', 'To fall'),
    ('จุด', 'chut', 'To light a fire'),
    ('กระดาน', 'kradan', 'A board, plank'),
    ('สอน', 'son', 'To teach'),
    ('ยก', 'yok', 'To lift, to raise'),
    ('เกิน', 'koen', 'To exceed'),
    ('ประมาณ', 'praman', 'Approximately'),
    ('ยอม', 'yom', 'To be willing, accede'),
    ('ขาด', 'khat', 'torn, broken, lacking'),
    ('แรง', 'raeng', 'Strength, power'),
    ('สิ', 'si', 'A particle used to suggest an action'),
    ('บท', 'bot', 'A lesson in a textbook, the text or lines of a play'),
    ('เจ้า', 'chao', 'Prince, ruler'),
    ('เจ้าของ', 'chaokhong', 'Owner'),
    ('ไฟฟ้า', 'faifa', 'Electricity'),
    ('หนังสือพิมพ์', 'nangsuephim', 'Newspaper'),
    ('ลอง', 'long', 'To try out'),
    ('เฉพาะ', 'chapho', 'Especially or exclusively for'),
    ('เช่น', 'chen', 'As, like, for example'),
    ('จน', 'chon', 'Until'),
    ('ประโยชน์', 'prayot', 'Use, usefulness'),
    ('ระยะ', 'raya', 'A stretch of distance or time'),
    ('เริ่ม', 'roem', 'To begin'),
    ('ต้น', 'ton', 'A beginning'),
    ('สนทนา', 'sonthana', 'Conversation'),
    ('ค่อย', 'khoi', 'Gradually, little by little'),
    ('ไม่ค่อย', 'maikhoi', 'Hardly, not very'),
    ('ปลอดภัย', 'plotphai', 'safe'),
    ('ระวัง', 'rawang', 'careful, beware'),
    ('กล้อง', 'klong', 'A tobacco pipe, camera, binoculars, telescope, microscope'),
    ('เสียง', 'siang', 'Sound'),
    ('ต่ำ', 'tam', 'Low (in pitch, elevation, or status)'),
    ('ชั้น', 'chan', 'A layer, storey, class, grade'),
    ('เล่า', 'lao', 'To tell, relate'),
    ('สะดวก', 'saduak', 'Convenient'),
    ('เดินทาง', 'doenthang', 'To travel'),
    ('ด่วน', 'duan', 'urgent, express'),
    ('ท่องเที่ยว', 'thongthiao', 'To tour, travel for pleasure'),
    ('บริเวณ', 'boriwen', 'Area, vicinity'),
    ('ทัน', 'than', 'on time'),
    ('อายุ', 'ayu', 'Age'),
    ('จำเป็น', 'champen', 'necessary'),
    ('ประวัติ', 'prawat', 'History, account, story'),
    ('โท', 'tho', 'Second rank'),
    ('นัด', 'nat', 'To make an appointment'),
    ('วิทยาศาสตร์', 'witthayasat', 'Science'),
    ('พร', 'phon', 'Blessings'),
    ('ดัง', 'dang', 'Like, as, according to'),
    ('พยายาม', 'phayayam', 'To try, make an attempt'),
    ('ชนิด', 'chanit', 'Kind, type, variety'),
    ('ตลอด', 'talot', 'Throughout'),
    ('ลงทะเบียน', 'longthabian', 'To register'),
    ('อุตสาหกรรม', 'utsahakam', 'Industry'),
    ('กระทรวง', 'krasuang', 'Government ministry'),
    ('บันทึก', 'banthuek', 'To note, to record'),
    ('ทะเบียน', 'thabian', 'A registration'),
    ('ญี่ปุ่น', 'yipun', 'Japan'),
    ('รู้สึก', 'rusuek', 'To feel'),
    ('เต็ม', 'tem', 'full'),
    ('ดนตรี', 'dontri', 'Music'),
    ('ละคร', 'lakhon', 'A play'),
    ('ศาสนา', 'satsana', 'Religion'),
    ('ตรวจ', 'truat', 'Trot (a province of Thailand)'),
    ('เหลือ', 'luea', 'left over, remaining'),
    ('เตรียม', 'triam', 'To prepare'),
    ('ชุด', 'chut', 'A set of something'),
    ('ประจำวัน', 'prachamwan', 'Daily'),
    ('สำเร็จ', 'samret', 'To complete, be successful'),
    ('สด', 'sot', 'fresh'),
    ('แต่ง', 'taeng', 'To adorn, decorate'),
    ('ลา', 'la', 'donkey'),
    ('กอง', 'kong', 'a pile of.....a troop of'),
    ('ปรับ', 'prap', 'to fine'),
    ('ยอมรับ', 'yomrap', 'to admit'),
    ('กฎหมาย', 'kotmai', 'law'),
    ('มุม', 'mum', 'corner'),
    ('ลูกค้า', 'lukkha', 'customer'),
    ('มาตรฐาน', 'matthan', 'measure'),
    ('รายได้', 'raidai', 'income, revenue'),
    ('อัตรา', 'attra', 'rate'),
    ('ป่า', 'pa', 'forest'),
    ('เกาะ', 'ko', 'island'),
    ('ข', 'kho', 'khor - khai'),
    ('ฉ', 'cha', 'chor - ching'),
    ('ถ', 'tha', 'thor - thung'),
    ('ผ', 'pha', 'phor - phyyng'),
    ('ษ', 'sa', 'sor - ryysii'),
    ('ภ', 'pha', 'phor - sampao'),
    ('ฮ', 'ha', 'hor - nok huuk'),
    ('กา', 'ka', 'crow'),
    ('รู', 'ru', 'hole'),
    ('กรม', 'krom', 'regiment, directorate'),
    ('หมวด', 'muat', 'Platoon'),
    ('หมู่', 'mu', 'squad'),
    ('เจอ', 'choe', 'face, meet'),
    ('โดยเฉพาะ', 'doichapho', 'especially'),
    ('มหาวิทยาลัย', 'mahawitthayalai', 'university'),
    ('ป้องกัน', 'pongkan', 'to protect'),
    ('ผลิต', 'phlit', 'to produce'),
    ('แหล่ง', 'laeng', 'source'),
    ('ที่อยู่', 'thiyu', 'address'),
    ('รัฐ', 'rat', 'State'),
    ('การเมือง', 'kanmueang', 'politics'),
    ('รัฐบาล', 'ratthaban', 'government'),
    ('นโยบาย', 'nayobai', 'policy'),
    ('เหตุการณ์', 'hetkan', 'incident'),
    ('คอมพิวเตอร์', 'khomphiotoe', 'computer'),
    ('ปฏิทิน', 'patithin', 'calendar'),
    ('ภาษาอังกฤษ', 'phasa-angkrit', 'English language'),
    ('ภาษาไทย', 'phasathai', 'Thai language'),
    ('พัก', 'phak', 'take a break'),
    ('ปล่อย', 'ploi', 'to release'),
    ('เครือข่าย', 'khrueakhai', 'network'),
    ('ตอนนี้', 'tonni', 'now'),
    ('ผลงาน', 'phonngan', '(body of) work'),
    ('วิเคราะห์', 'wikhro', 'analyze'),
    ('คณะกรรมการ', 'khanakammakan', 'committee'),
    ('ระยะเวลา', 'rayawela', 'interval'),
    ('วิธีการ', 'withikan', 'procedure'),
    ('พิสูจน์', 'phisut', 'to prove'),
    ('ฐาน', 'than', 'base'),
    ('ศิลปะ', 'sinlapa', 'art'),
    ('กระ', 'kra', 'freckle'),
    ('ขี้', 'khi', 'poop'),
    ('ข้อ', 'kho', 'joint'),
    ('อก', 'ok', 'chest'),
    ('คอ', 'kho', 'neck'),
    ('หัวใจ', 'huachai', 'heart'),
    ('ลิขสิทธิ์', 'liksit', 'copyright'),
    ('บทความ', 'botkhwam', 'article'),
    ('สงวนลิขสิทธิ์', 'sa-nguanliksit', 'to copyright'),
    ('ฉบับ', 'chabap', 'edition'),
    ('ประสบการณ์', 'prasopkan', 'experience'),
    ('เศรษฐกิจ', 'setthakit', 'economy'),
    ('ผลิตภัณฑ์', 'phlitphan', 'product'),
    ('อุปกรณ์', 'upakon', 'equipment'),
    ('การตลาด', 'kantalat', 'marketing'),
    ('รับผิดชอบ', 'rapphitchop', 'to be responsible for'),
    ('ลงทุน', 'longthun', 'to invest'),
    ('ช่อง', 'chong', 'channel'),
    ('รายงาน', 'rai-ngan', 'to report'),
    ('เหนือ', 'nuea', 'north'),
    ('ใต้', 'tai', 'south'),
    ('โปรแกรม', 'prokraem', 'program'),
    ('ออกแบบ', 'okbaep', 'to design'),
    ('โอ่ง', 'ong', 'large water jar'),
    ('คำถาม', 'khamtham', 'question'),
    ('คำตอบ', 'khamtop', 'answer'),
    ('คะแนน', 'khanaen', 'grade'),
    ('อาจารย์', 'achan', 'teacher (respectful)'),
    ('นักศึกษา', 'naksueksa', '(university) student'),
    ('อาคาร', 'akhan', 'building'),
    ('เรียนรู้', 'rianru', 'to learn'),
    ('สอบ', 'sop', 'to test'),
    ('ตี', 'ti', 'to beat'),
    ('โดนัท', 'donat', 'donut'),
    ('สภา', 'sapha', 'council'),
    ('โหวต', 'hot', 'to vote (informal)'),
    ('รูปภาพ', 'rupphap', 'picture'),
    ('พนักงาน', 'phanakngan', 'clerk'),
    ('รับสมัคร', 'rapsamakkhon', 'hiring'),
    ('พระ', 'phra', 'monk (informal)'),
    ('วา', 'wa', 'wa (2 meters)'),
    ('โน้ต', 'not', 'note'),
    ('ธรรมชาติ', 'thammachat', 'nature'),
    ('เอกสาร', 'eksan', 'document'),
    ('วัย', 'wai', 'age (stage of life)'),
    ('นาง', 'nang', 'Mrs'),
    ('มารยาท', 'marayat', 'manners'),
    ('สำนักงาน', 'samnakngan', 'office building'),
    ('เชื่อ', 'chuea', 'to believe'),
    ('สาขา', 'sakha', 'branch'),
    ('บัญชี', 'banchi', 'account'),
    ('ฝาก', 'fak', 'to deposit'),
    ('สุขภาพ', 'sukphap', 'health'),
    ('ประชาสัมพันธ์', 'prachasamphan', 'reception'),
    ('มอง', 'mong', 'to look'),
    ('รอบ', 'rop', 'showing'),
    ('กติกา', 'katika', 'rules'),
    ('ทีม', 'thim', 'team'),
    ('เขต', 'khet', 'district (Bangkok)'),
    ('อำเภอ', 'amphoe', 'district (outside Bangkok)'),
    ('เชียงใหม่', 'chiangmai', 'Chiang Mai'),
    ('อดีต', 'adit', 'past'),
    ('ปัจจุบัน', 'patchuban', 'present'),
    ('อนาคต', 'anakhot', 'future'),
    ('เปลี่ยน', 'plian', 'to change'),
    ('เปลี่ยนแปลง', 'plianplaeng', 'to change (elegant)'),
    ('ปรับปรุง', 'prapprung', 'to improve'),
    ('ชำระ', 'chamra', 'to revise (formal)'),
    ('ขยาย', 'khayai', 'to expand'),
    ('ถุย', 'thui', 'to spit'),
    ('วาง', 'wang', 'to set down'),
    ('กด', 'kot', 'to press'),
    ('แอบ', 'aep', 'to hide (intransitive)'),
    ('จำหน่าย', 'chamnai', 'to distribute'),
    ('กล่าว', 'klao', 'to speak'),
    ('คุย', 'khui', 'to converse'),
    ('สื่อสาร', 'suesan', 'to communicate'),
    ('ล่า', 'la', 'to hunt'),
    ('จัดการ', 'chatkan', 'to manage'),
    ('วิจัย', 'wichai', 'to research'),
    ('พร้า', 'phra', 'machete'),
    ('ผู้ใช้', 'phuchai', 'user'),
    ('ลิงค์', 'ling', 'link'),
    ('เข้าสู่ระบบ', 'khaosurabop', 'login'),
    ('รหัสผ่าน', 'rahatphan', 'password'),
    ('ตั้งกระทู้', 'tangkrathu', 'start a thread'),
    ('ถูกต้อง', 'thuktong', 'accurate, (correct)'),
    ('ประกอบ', 'prakop', 'assemble, (put together)'),
    ('เจ้าหน้าที่', 'chaonathi', 'authorities, (government)'),
    ('อัตโนมัติ', 'attonomat', 'automatic'),
    ('ประเภท', 'praphet', 'category'),
    ('อ้างอิง', 'ang-ing', 'cite'),
    ('ชุมชน', 'chumchon', 'community'),
    ('ยืนยัน', 'yuenyan', 'confirm'),
    ('สัญญา', 'sanya', 'contract, n'),
    ('วัฒนธรรม', 'watthanatham', 'culture, (society)'),
    ('แน่นอน', 'naenon', 'definite'),
    ('เน้น', 'nen', 'emphasize, (focus)'),
    ('สุดท้าย', 'sutthai', 'final, adj'),
    ('พื้นฐาน', 'phuenthan', 'foundation, n. (figurative)'),
    ('หน้าที่', 'nathi', 'function, n'),
    ('รุ่น', 'run', 'generation, n. (conceptual)'),
    ('สถาบัน', 'sathaban', 'institute, n'),
    ('ตรวจสอบ', 'truatsop', 'investigate'),
    ('ประเด็น', 'praden', 'issue, n. (topic)'),
    ('สื่อ', 'sue', 'media, n. (pl. of medium)'),
    ('เกิดขึ้น', 'koetkhuen', 'occur'),
    ('เข้าร่วม', 'khaoruam', 'participate'),
    ('โครงการ', 'khrongkan', 'project, n'),
    ('ส่งเสริม', 'songsoem', 'promote'),
    ('เผยแพร่', 'phoeiphrae', 'publish, (disseminate)'),
    ('ระบุ', 'rabu', 'specify'),
    ('สภาพ', 'saphap', 'status, (condition)'),
    ('รูปแบบ', 'rupbaep', 'style, n'),
    ('สรุป', 'sap', 'summarize'),
    ('ทีมงาน', 'thimngan', 'team, (work)'),
    ('เทคโนโลยี', 'theknoloiyi', 'technology'),
    ('สูงสุด', 'sungsut', 'ultimate, (highest)'),
    ('สถิติ', 'sathiti', 'statistic'),
    ('หัวข้อ', 'huakho', 'topic'),
    ('จ๊ะ', 'cha', 'Polite particle'),
    ('อ้วน', 'uan', 'fat'),
    ('หนา', 'na', 'Thick'),
    ('เหรอ', 'roe', "A particle used to ask for a confirmation. 'Am I right..."),
    ('โทษ', 'thot', 'To blame, punishment'),
    ('หนู', 'nu', 'Mouse'),
    ('ข้างหน้า', 'khangna', 'In front of'),
    ('อีกที', 'ikthi', 'Again, another time'),
    ('ข้างบน', 'khangbon', 'Upstairs'),
    ('อบ', 'op', 'To roast or bake'),
    ('แห้ง', 'haeng', 'dry'),
    ('ทู', 'thu', 'A fish resembling a herring or mackerel'),
    ('ผ้า', 'pha', 'Cloth'),
    ('เปล่า', 'plao', 'Empty. Used to reject a wrong assumption. No'),
    ('โรง', 'rong', 'A large shed or hall'),
    ('หลาน', 'lan', 'Nephew, niece, grandchild. (Younger relation two steps...'),
    ('ดึง', 'dueng', 'To pull'),
    ('นาฬิกา', 'nalika', "Watch, clock, o'clock (in the 24 hour system)"),
    ('เลข', 'lek', 'Number'),
    ('ซอย', 'soi', 'Soi, lane'),
    ('เท่าไร', 'thaorai', 'How much? How many?'),
    ('จาน', 'chan', 'A plate'),
    ('แก้ว', 'kaeo', 'Glass, a glass'),
    ('เวียดนาม', 'wiatnam', 'Vietnam'),
    ('เขียว', 'khiao', 'Green'),
    ('เหลือง', 'lueang', 'Yellow'),
    ('ก้าว', 'kao', 'A step, to step'),
    ('เก่ง', 'keng', 'skillful or good at something'),
    ('กระดาษ', 'kradat', 'Paper'),
    ('หน้าต่าง', 'natang', 'Window (the opening and shutters, not the glass)'),
    ('ประตู', 'pratu', 'Door'),
    ('นิ้ว', 'nio', 'Fingers, toes, inches'),
    ('น้ำมัน', 'namman', 'Blue'),
    ('อเมริกา', 'amerika', 'America'),
    ('ฉาย', 'chai', 'To shine a light'),
    ('ทอง', 'thong', 'Gold'),
    ('ปืน', 'puen', 'Gun'),
    ('โต๊ะ', 'to', 'Table, desk'),
    ('ด้วยกัน', 'duaikan', 'Together'),
    ('ทาน', 'than', 'Short for รับประทาน'),
    ('ขอนแก่น', 'khonkaen', 'Khon Kaen (a province of Thailand)'),
    ('ป้า', 'pa', "Father or mother's older sister, aunt"),
    ('ครึ่ง', 'khrueng', 'Half'),
    ('เดี๋ยว', 'diao', 'In a moment'),
    ('ตกลง', 'toklong', 'To come to an agreement, decide'),
    ('เปรียบเทียบ', 'priapthiap', 'To compare'),
    ('หิน', 'hin', 'Rock, stone'),
    ('แผ่น', 'phaen', "A 'sheet' of something. Classifier for 'sheet' like things"),
    ('เส้น', 'sen', "A line. Classifier for 'string' like things"),
    ('หอม', 'hom', 'To smell good'),
    ('แข็ง', 'khaeng', 'hard (not soft)'),
    ('เกือก', 'kueak', 'Shoes (vulgar)'),
    ('น้ำตาล', 'namtan', 'Sugar'),
    ('ทุ่ม', 'thum', "O'clock (used only with hours from evening to midnight)"),
    ('ชิ้น', 'chin', 'A piece of something'),
    ('แปล', 'plae', 'To mean, to translate'),
    ('ทั้งสอง', 'thangsong', 'Both'),
    ('ไหว', 'wai', 'To be physically able, to be up to'),
    ('จอด', 'chot', 'To park, bring to a stop'),
    ('ขับ', 'khap', 'To drive'),
    ('คอย', 'khoi', 'To wait for'),
    ('แพ้', 'phae', 'To lose to someone (as in a game)'),
    ('ตังค์', 'tang', 'The usual pronunciation of satang'),
    ('ตู้', 'tu', 'Cupboard, closet'),
    ('ยาม', 'yam', 'A guard, watchman'),
    ('เล่ม', 'lem', 'Classifier for books'),
    ('ด่า', 'da', 'To curse, scold'),
    ('ปิ้ง', 'ping', 'To toast'),
    ('ปู', 'pu', 'Crab'),
    ('คัน', 'khan', 'Classifier for cars'),
    ('ล้อ', 'lo', 'Wheel'),
    ('ไปรษณีย์', 'praisani', 'Post office'),
    ('ราว', 'rao', 'Approximately'),
    ('เมตร', 'met', 'Meter (39.37 inches)'),
    ('เกือบ', 'kueap', 'Almost, approximately, being close to'),
    ('ศพ', 'sop', 'A corpse'),
    ('ถ่ายรูป', 'thairup', 'To photograph'),
    ('เสื้อ', 'suea', 'Upper garment, shirt, blouse coat, sweater'),
    ('ดัน', 'dan', 'To push'),
    ('กำลังจะ', 'kamlangcha', 'about to, on the point of'),
    ('เสื้อผ้า', 'sueapha', 'Clothing'),
    ('ฟัน', 'fan', 'Teeth'),
    ('รบกวน', 'ropkuan', 'To bother'),
    ('เหล็ก', 'lek', 'Iron'),
    ('กุมภาพันธ์', 'kumphaphan', 'February'),
    ('มกราคม', 'mokrakhom', 'January'),
    ('ธันวาคม', 'thanwakhom', 'December'),
    ('ชัด', 'chat', 'plain, clear, distinct'),
    ('ยิ้ม', 'yim', 'To smile'),
    ('บังคับ', 'bangkhap', 'To force'),
    ('เงียบ', 'ngiap', 'quiet'),
    ('เมษายน', 'mesayon', 'April'),
    ('มีนาคม', 'minakhom', 'March'),
    ('พฤษภาคม', 'phritsakhom', 'May'),
    ('ชวน', 'chuan', 'To invite'),
    ('ยกเว้น', 'yokwen', 'To except'),
    ('กรกฎาคม', 'korokdakhom', 'July'),
    ('มิถุนายน', 'mithunayon', 'June'),
    ('บ้า', 'ba', 'Crazy'),
    ('แถว', 'thaeo', 'A row'),
    ('รับประกัน', 'rapprakan', 'To guarantee'),
    ('แตกต่าง', 'taektang', 'To differ'),
    ('พื้น', 'phuen', 'Floor'),
    ('ธรรมดา', 'thammada', 'Normal, ordinary, common'),
    ('คิดถึง', 'khitthueng', 'To think about someone (used in the same situations whe...'),
    ('แต่งงาน', 'taengngan', 'To marry, get married'),
    ('นึก', 'nuek', 'To think'),
    ('แก', 'kae', 'He, she (respectful)'),
    ('นอกจาก', 'nokchak', 'Outside of, besides'),
    ('อ่อน', 'on', 'soft, tender, young, weak'),
    ('หรอก', 'rok', 'A particle used to straighten out a wrong impression. U...'),
    ('เชิ้ต', 'choet', "(From the English 'shirt'.)"),
    ('กว้าง', 'kwang', 'wide, broad'),
    ('ซัก', 'sak', 'To wash clothing, launder'),
    ('เกินไป', 'koenpai', 'Too, excessively'),
    ('นุ่ง', 'nung', 'To wear or put on a lower garment'),
    ('ถ้าจะ', 'tha cha', 'It appears, there is some evidence or reason to think'),
    ('ยี่ห้อ', 'yiho', 'Brand, make, trademark'),
    ('กี้', 'ki', 'A moment ago'),
    ('ล้าง', 'lang', "To wash (not used with 'hair' or 'clothes')"),
    ('ตาก', 'tak', 'To expose to the sun, air, or wind'),
    ('หญ้า', 'ya', 'Grass'),
    ('เช่า', 'chao', 'To rent'),
    ('เฝ้า', 'fao', 'To guard, watch, keep an eye on'),
    ('ยักคิ้ว', 'yakkhio', 'To raise the eyebrows'),
    ('ลำบาก', 'lambak', 'Inconvenient, difficult'),
    ('ถึงจะ', 'thueng cha', 'Even though'),
    ('อย่างมาก', 'yang mak', 'At most'),
    ('อย่างน้อย', 'yang noi', 'At least'),
    ('กล่อง', 'klong', 'A small box'),
    ('ส้อม', 'som', 'A fork'),
    ('บิน', 'bin', 'To fly'),
    ('บก', 'bok', 'Land (as opposed to sea)'),
    ('แม่น้ำ', 'maenam', 'River'),
    ('กระจก', 'krachok', 'Window pane, mirror'),
    ('สมัย', 'samai', 'An era'),
    ('สนาม', 'sanam', 'A yard, court, field'),
    ('ทันสมัย', 'thansamai', 'Up to date'),
    ('เจ็บ', 'chep', 'To hurt, be hurt'),
    ('ขำ', 'kham', 'To be funny, laugh'),
    ('พยาบาล', 'phayaban', 'To tend, to nurse'),
    ('แผนที่', 'phaenthi', 'A map'),
    ('สมุด', 'samut', 'A notebook'),
    ('พอดี', 'phodi', 'Just right'),
    ('โทรทัศน์', 'thorathat', 'Television'),
    ('เถอะ', 'thoe', "Let's. Marks an imperative or entreaty"),
    ('เบา', 'bao', 'To he light in weight'),
    ('เอก', 'ek', 'First rank'),
    ('ภูมิ', 'phum', 'Earth, place (in compounds)'),
    ('ประวัติศาสตร์', 'prawattisat', 'The field or subject of History'),
    ('ปริญญา', 'parinya', 'An academic degree'),
    ('ศาสตร์', 'sat', "A suffix meaning 'field of knowledge'. -ology"),
    ('ตรี', 'tri', 'Third rank'),
    ('ท้าย', 'thai', 'The end, the last of a series'),
    ('แพทย์', 'phaet', 'Medical doctor (formal)'),
    ('วิทยา', 'witthaya', 'Knowledge (used mainly in compounds)'),
    ('คำศัพท์', 'khamsap', 'Vocabulary'),
    ('โครงสร้าง', 'khrongsang', 'Structure'),
    ('นคร', 'nakhon', 'City'),
    ('เลื่อน', 'luean', 'To shift, slide, or move in position, time, or grade'),
    ('จดหมาย', 'chotmai', 'A letter, mail'),
    ('อัด', 'at', 'To compress'),
    ('ค่อน', 'khon', 'More than half'),
    ('เหล่านี้', 'laoni', 'These'),
    ('พอใจ', 'phochai', 'satisfied'),
    ('โต้', 'to', 'To counter, back and forth'),
    ('เกษตร', 'kaset', 'Agriculture'),
    ('สาธารณสุข', 'satharansuk', 'Public Heath'),
    ('ยุติธรรม', 'yutitham', 'Justice'),
    ('ข้าม', 'kham', 'To cross'),
    ('ย้าย', 'yai', 'To relocate'),
    ('ถอด', 'thot', 'To take off'),
    ('ได้ยิน', 'daiyin', 'To hear'),
    ('หลับ', 'lap', 'To close the eyes'),
    ('ชนะ', 'chana', 'To win'),
    ('ฝรั่งเศส', 'frangset', 'France, French'),
    ('เกาหลี', 'kaoli', 'Korea'),
    ('เรียบร้อย', 'riaproi', 'in good condition, all set'),
    ('เติม', 'toem', 'To add to, fill'),
    ('ยาง', 'yang', 'Rubber, a tire'),
    ('ปลูก', 'pluk', 'To plant crops'),
    ('ร้อง', 'rong', 'To cry out, yell'),
    ('เพชรบูรณ์', 'phetbun', 'Phetchabun (a province of Thailand)'),
    ('พิษณุโลก', 'phitsanulok', 'Phitsanulok (a province of Thailand)'),
    ('แพร่', 'phrae', 'Phrae (a province of Thailand)'),
    ('ภูเก็ต', 'phuket', 'Phuket (a province of Thailand)'),
    ('ราชบุรี', 'ratburi', 'Ratchaburi (a province of Thailand)'),
    ('ระนอง', 'ranong', 'Ranong (a province of Thailand)'),
    ('ระยอง', 'rayong', 'Rayong (a province of Thailand)'),
    ('สมุทรปราการ', 'samutprakan', 'Samut Prakan (a province of Thailand)'),
    ('สระบุรี', 'saburi', 'Saraburi (a province of Thailand)'),
    ('สงขลา', 'songkhla', 'Songkhla (a province of Thailand)'),
    ('สุโขทัย', 'sukhothai', 'Sukhothai (a province of Thailand)'),
    ('สุรินทร์', 'surin', 'Surin (a province of Thailand)'),
    ('ตรัง', 'trang', 'Trang (a province of Thailand)'),
    ('ยะลา', 'yala', 'Yala (a province of Thailand)'),
    ('เพชรบุรี', 'phetburi', 'Phetchaburi (a province of Thailand, also a road in Ban...'),
    ('สังเกต', 'sangket', 'To notice'),
    ('ตั้งใจ', 'tangchai', 'To intend'),
    ('แล้วแต่', 'laeotae', 'Depending on'),
    ('นับ', 'nap', 'To count'),
    ('สำเร็จรูป', 'samretrup', 'Ready-made'),
    ('แต่งตัว', 'taengtua', 'To dress, apply cosmetics, etc'),
    ('สะอาด', 'sa-at', 'clean'),
    ('กรรม', 'kam', 'karma'),
    ('ธรรม', 'tham', 'religious teaching, righteousness'),
    ('บุญ', 'bun', 'merit, good deed'),
    ('โรงงาน', 'rongngan', 'factory'),
    ('สีกรมท่า', 'sikromtha', 'navy blue'),
    ('แข็งแรง', 'khaengraeng', 'strong'),
    ('ปฏิเสธ', 'patiset', 'to deny'),
    ('กล่าวหา', 'klaoha', 'to accuse'),
    ('ภาษี', 'phasi', 'tax'),
    ('มูลค่า', 'munkha', 'value'),
    ('รัฐวิสาหกิจ', 'ratthawisahakit', 'state enterprise'),
    ('ส่งออก', 'song-ok', 'export'),
    ('การเลือกตั้ง', 'kanlueaktang', 'election'),
    ('ผู้สมัคร', 'phusamakkhon', 'candidate'),
    ('ทรัพยากร', 'sapphayakon', 'resources'),
    ('สิ่งแวดล้อม', 'singwaetlom', 'environment'),
    ('อนุรักษ์', 'anurak', 'to preserve'),
    ('งง', 'ngong', 'confused'),
    ('อาย', 'ai', 'embarrassed'),
    ('เศร้า', 'sao', 'sad'),
    ('จอง', 'chong', 'reserve'),
    ('กรอบ', 'krop', 'crispy'),
    ('ฐ', 'tha', 'thor- thaan'),
    ('ข้อตกลง', 'khotoklong', 'agreement'),
    ('ความช่วยเหลือ', 'khwamchuailuea', 'assistance'),
    ('ความมั่นคง', 'khwammankhong', 'security'),
    ('ความร่วมมือ', 'khwamruammue', 'cooperation'),
    ('ความสัมพันธ์', 'khwamsamphan', 'relation'),
    ('ผลกระทบ', 'phonkrathop', 'an impact'),
    ('คุณสมบัติ', 'khunsombat', 'requirement, qualification'),
    ('เพศ', 'phet', 'gender'),
    ('ฆ', 'kha', 'khor - rakhang'),
    ('ฑ', 'tha', 'thor - mon thoo'),
    ('มาหา', 'maha', 'come to see or visit'),
    ('ฎ', 'ta', 'dor- chada'),
    ('ฏ', 'ta', 'tor- patak'),
    ('การแข่งขัน', 'kankhaengkhan', 'tournament'),
    ('ซ้ำ', 'sam', 'repeatedly'),
    ('เรียกว่า', 'riak wa', 'to be called'),
    ('ไปหา', 'paiha', 'go to see'),
    ('วัยรุ่น', 'wairun', 'teenager'),
    ('ไร่', 'rai', 'plantation'),
    ('น้า', 'na', 'aunt/uncle(younger than mother)'),
    ('นามสกุล', 'namsakun', 'last name'),
    ('นายกรัฐมนตรี', 'naikratthamontri', 'prime minister'),
    ('ปกครอง', 'pokkhrong', 'to government'),
    ('รัฐธรรมนูญ', 'ratthathammun', 'constitution'),
    ('รัฐมนตรี', 'ratthamontri', 'ministers'),
    ('ประชาธิปไตย', 'prachathipatai', 'democracy'),
    ('สถานการณ์', 'sathankan', 'situation'),
    ('อำนาจ', 'amnat', 'power'),
    ('คลอง', 'khlong', 'canal'),
    ('สะพาน', 'saphan', 'bridge'),
    ('ทีวี', 'thiwi', 'television'),
    ('พิษ', 'phit', 'toxin'),
    ('ยิง', 'ying', 'to shoot'),
    ('ระเบิด', 'raboet', 'bomb'),
    ('รุนแรง', 'runraeng', 'violent'),
    ('เป้าหมาย', 'paomai', 'objective, goal'),
    ('วันพฤหัสบดี', 'wan pharuehatbodi', 'Thursday'),
    ('ขน', 'khon', 'hair'),
    ('สมอง', 'samong', 'brain'),
    ('โบราณ', 'boran', 'ancient'),
    ('แนวคิด', 'naeokhit', 'concept'),
    ('วิจารณ์', 'wichan', 'criticize'),
    ('มีประสิทธิภาพ', 'miprasitthiphap', 'effective'),
    ('วัตถุ', 'watthu', 'object'),
    ('วัตถุประสงค์', 'watthuprasong', 'objective'),
    ('กระบวนการ', 'krabuankan', 'process'),
    ('สัมมนา', 'sammana', 'seminar'),
    ('ร่าง', 'rang', 'to draft'),
    ('ทดลอง', 'thotlong', 'to experiment'),
    ('ทหาร', 'thahan', 'solder'),
    ('ยักษ์', 'yak', 'giant'),
    ('ศาลา', 'sala', 'pavilion'),
    ('มด', 'mot', 'ant'),
    ('พันธุ์', 'phan', 'breed (of animal)'),
    ('สุนัข', 'sunak', 'dog (elegant)'),
    ('ขัน', 'khan', 'to crow'),
    ('ศิลปิน', 'sinlapin', 'artist'),
    ('นักร้อง', 'nakrong', 'singer'),
    ('ภาพยนตร์', 'phapphayon', 'film (motion picture)'),
    ('เวที', 'wethi', 'stage'),
    ('ร่างกาย', 'rangkai', 'body (elegant)'),
    ('ผิว', 'phio', 'skin'),
    ('สายตา', 'saita', 'eyesight'),
    ('เลือด', 'lueat', 'blood'),
    ('ไต', 'tai', 'kidney'),
    ('จู๋', 'chu', 'penis (cutesy)'),
    ('ปก', 'pok', 'cover'),
]
