# -*- coding: utf-8 -*-
"""Thai vocabulary deck, split into levels: (Thai, romanization, English).

Romanization follows one consistent learner system (Paiboon-style, ASCII
vowels) so every word can be read the same way:

  Tones   a = mid    à = low    â = falling    á = high    ǎ = rising
  Vowels  doubled letters are long (aa, ii, uu, ee, oo); ue = ึ/ื,
          er = เ-อ, ae = แ, aw = ออ, ia = เ-ีย, uea = เ-ือ, ua = -ัว
  Consonants  g = ก, dt = ต, bp = ป, j = จ (all unaspirated);
          kh, th, ph, ch are the breathy ones (ข/ค, ท/ถ, พ/ผ, ช/ฉ)

Syllables inside one word are joined with "-", separate words with spaces.
"""

LEVELS = [
    ("beginner", "Beginner — survival basics", [
        # greetings & politeness
        ('สวัสดี', 'sà-wàt-dii', 'Hello / Goodbye'),
        ('ขอบคุณ', 'khàwp-khun', 'Thank you'),
        ('ขอบคุณมาก', 'khàwp-khun mâak', 'Thank you very much'),
        ('ขอโทษ', 'khǎw-thôot', 'Sorry / Excuse me'),
        ('ไม่เป็นไร', 'mâi bpen rai', "Never mind / You're welcome"),
        ('ครับ', 'khráp', 'Polite ending (male speaker)'),
        ('ค่ะ', 'khâ', 'Polite ending (female speaker, statements)'),
        ('คะ', 'khá', 'Polite ending (female speaker, questions)'),
        ('ลาก่อน', 'laa-gàwn', 'Goodbye (for a long time)'),
        ('แล้วเจอกันใหม่', 'láew jer gan mài', 'See you again'),
        ('โชคดี', 'chôok dii', 'Good luck'),
        ('สบายดีไหม', 'sà-baai dii mǎi', 'How are you?'),
        ('สบายดี', 'sà-baai dii', "I'm fine"),
        ('ยินดีที่ได้รู้จัก', 'yin-dii thîi dâai rúu-jàk', 'Nice to meet you'),
        ('คุณชื่ออะไร', 'khun chûe à-rai', "What's your name?"),
        ('ฉันชื่อ…', 'chǎn chûe …', 'My name is …'),
        # yes / no / can
        ('ใช่', 'châi', "Yes / That's right"),
        ('ไม่ใช่', 'mâi châi', "No / That's not right"),
        ('ไม่', 'mâi', 'Not / No'),
        ('ได้', 'dâai', 'Can / OK'),
        ('ไม่ได้', 'mâi dâai', 'Cannot'),
        ('มี', 'mii', 'To have / There is'),
        ('ไม่มี', 'mâi mii', "Don't have / There isn't"),
        ('รู้', 'rúu', 'To know'),
        ('ไม่รู้', 'mâi rúu', "I don't know"),
        ('เข้าใจ', 'khâo-jai', 'To understand'),
        ('ไม่เข้าใจ', 'mâi khâo-jai', "I don't understand"),
        # survival phrases
        ('ช่วยด้วย', 'chûai dûai', 'Help!'),
        ('ห้องน้ำอยู่ที่ไหน', 'hâwng-náam yùu thîi-nǎi', 'Where is the bathroom?'),
        ('พูดช้าๆ หน่อย', 'phûut cháa-cháa nòi', 'Please speak slowly'),
        ('อีกครั้ง', 'ìik khráng', 'Again / One more time'),
        ('เท่าไหร่', 'thâo-rài', 'How much?'),
        ('แพงไป', 'phaeng bpai', 'Too expensive'),
        ('ลดได้ไหม', 'lót dâai mǎi', 'Can you give a discount?'),
        ('เช็คบิล', 'chék bin', 'The bill, please'),
        # pronouns
        ('ผม', 'phǒm', 'I / me (male)'),
        ('ฉัน', 'chǎn', 'I / me (female or casual)'),
        ('ดิฉัน', 'dì-chǎn', 'I / me (female, formal)'),
        ('คุณ', 'khun', 'You (polite)'),
        ('เขา', 'khǎo', 'He / She / They'),
        ('เรา', 'rao', 'We / us'),
        ('พวกเขา', 'phûak-khǎo', 'They / them'),
        # this / that / question words
        ('นี่', 'nîi', 'This (one here)'),
        ('นั่น', 'nân', 'That (one there)'),
        ('ที่นี่', 'thîi-nîi', 'Here'),
        ('ที่นั่น', 'thîi-nân', 'There'),
        ('อะไร', 'à-rai', 'What'),
        ('ใคร', 'khrai', 'Who'),
        ('ที่ไหน', 'thîi-nǎi', 'Where'),
        ('เมื่อไหร่', 'mûea-rài', 'When'),
        ('ทำไม', 'tham-mai', 'Why'),
        ('ยังไง', 'yang-ngai', 'How (casual)'),
        ('กี่', 'gìi', 'How many'),
        ('อันไหน', 'an-nǎi', 'Which one'),
        # numbers
        ('ศูนย์', 'sǔun', 'Zero'),
        ('หนึ่ง', 'nùeng', 'One'),
        ('สอง', 'sǎwng', 'Two'),
        ('สาม', 'sǎam', 'Three'),
        ('สี่', 'sìi', 'Four'),
        ('ห้า', 'hâa', 'Five'),
        ('หก', 'hòk', 'Six'),
        ('เจ็ด', 'jèt', 'Seven'),
        ('แปด', 'bpàet', 'Eight'),
        ('เก้า', 'gâo', 'Nine'),
        ('สิบ', 'sìp', 'Ten'),
        ('สิบเอ็ด', 'sìp-èt', 'Eleven'),
        ('ยี่สิบ', 'yîi-sìp', 'Twenty'),
        ('ร้อย', 'rói', 'Hundred'),
        ('พัน', 'phan', 'Thousand'),
        ('หมื่น', 'mùen', 'Ten thousand'),
        ('แสน', 'sǎen', 'Hundred thousand'),
        ('ล้าน', 'láan', 'Million'),
        # core verbs
        ('ไป', 'bpai', 'To go'),
        ('มา', 'maa', 'To come'),
        ('กิน', 'gin', 'To eat'),
        ('ดื่ม', 'dùem', 'To drink'),
        ('นอน', 'nawn', 'To sleep / lie down'),
        ('ทำ', 'tham', 'To do / make'),
        ('ดู', 'duu', 'To look / watch'),
        ('ฟัง', 'fang', 'To listen'),
        ('พูด', 'phûut', 'To speak'),
        ('อ่าน', 'àan', 'To read'),
        ('เขียน', 'khǐan', 'To write'),
        ('ซื้อ', 'súe', 'To buy'),
        ('ขาย', 'khǎai', 'To sell'),
        ('ชอบ', 'châwp', 'To like'),
        ('รัก', 'rák', 'To love'),
        ('อยาก', 'yàak', 'To want to'),
        ('ต้องการ', 'dtâwng-gaan', 'To want / need'),
        ('ขอ', 'khǎw', 'To ask for / May I have'),
        ('ให้', 'hâi', 'To give'),
        ('อยู่', 'yùu', 'To be at / live / stay'),
        ('เป็น', 'bpen', 'To be (something)'),
        ('รอ', 'raw', 'To wait'),
        ('เรียน', 'rian', 'To study'),
        ('ทำงาน', 'tham-ngaan', 'To work'),
        ('เดิน', 'dern', 'To walk'),
        ('นั่ง', 'nâng', 'To sit'),
        # food basics
        ('ข้าว', 'khâao', 'Rice / a meal'),
        ('น้ำ', 'náam', 'Water'),
        ('อาหาร', 'aa-hǎan', 'Food'),
        ('อร่อย', 'à-ròi', 'Delicious'),
        ('เผ็ด', 'phèt', 'Spicy'),
        ('ไม่เผ็ด', 'mâi phèt', 'Not spicy'),
        ('หิว', 'hǐu', 'Hungry'),
        ('อิ่ม', 'ìm', 'Full (after eating)'),
        ('กาแฟ', 'gaa-fae', 'Coffee'),
        ('ชา', 'chaa', 'Tea'),
        # describing words
        ('ดี', 'dii', 'Good'),
        ('ใหญ่', 'yài', 'Big'),
        ('เล็ก', 'lék', 'Small'),
        ('ร้อน', 'ráwn', 'Hot'),
        ('หนาว', 'nǎao', 'Cold (weather)'),
        ('สวย', 'sǔai', 'Beautiful'),
        ('แพง', 'phaeng', 'Expensive'),
        ('ถูก', 'thùuk', 'Cheap / Correct'),
        ('มาก', 'mâak', 'Very / A lot'),
        ('นิดหน่อย', 'nít-nòi', 'A little bit'),
        ('ใหม่', 'mài', 'New'),
        ('เก่า', 'gào', 'Old (things)'),
        ('สนุก', 'sà-nùk', 'Fun'),
        ('เหนื่อย', 'nùeai', 'Tired'),
        # time & places
        ('วันนี้', 'wan-níi', 'Today'),
        ('พรุ่งนี้', 'phrûng-níi', 'Tomorrow'),
        ('เมื่อวาน', 'mûea-waan', 'Yesterday'),
        ('ตอนนี้', 'dtawn-níi', 'Now'),
        ('บ้าน', 'bâan', 'House / Home'),
        ('ห้องน้ำ', 'hâwng-náam', 'Bathroom / Toilet'),
        ('ร้านอาหาร', 'ráan aa-hǎan', 'Restaurant'),
        ('โรงแรม', 'roong-raem', 'Hotel'),
        ('ตลาด', 'dtà-làat', 'Market'),
    ]),

    ("elementary", "Elementary — everyday life", [
        # family & people
        ('พ่อ', 'phâw', 'Father'),
        ('แม่', 'mâe', 'Mother'),
        ('พี่', 'phîi', 'Older sibling'),
        ('น้อง', 'náwng', 'Younger sibling'),
        ('ลูก', 'lûuk', 'Child (son / daughter)'),
        ('สามี', 'sǎa-mii', 'Husband'),
        ('ภรรยา', 'phan-rá-yaa', 'Wife'),
        ('เพื่อน', 'phûean', 'Friend'),
        ('แฟน', 'faen', 'Boyfriend / Girlfriend'),
        ('ครอบครัว', 'khrâwp-khrua', 'Family'),
        ('ปู่', 'bpùu', "Grandfather (father's side)"),
        ('ย่า', 'yâa', "Grandmother (father's side)"),
        ('ตา', 'dtaa', "Eye / Grandfather (mother's side)"),
        ('ยาย', 'yaai', "Grandmother (mother's side)"),
        ('ลุง', 'lung', "Uncle (older than one's parent)"),
        ('ป้า', 'bpâa', "Aunt (older than one's parent)"),
        ('เด็ก', 'dèk', 'Child / Kid'),
        ('ผู้ชาย', 'phûu-chaai', 'Man'),
        ('ผู้หญิง', 'phûu-yǐng', 'Woman'),
        ('คน', 'khon', 'Person'),
        # food & drink
        ('ไก่', 'gài', 'Chicken'),
        ('หมู', 'mǔu', 'Pork'),
        ('เนื้อ', 'núea', 'Beef / Meat'),
        ('ปลา', 'bplaa', 'Fish'),
        ('กุ้ง', 'gûng', 'Shrimp'),
        ('ไข่', 'khài', 'Egg'),
        ('ผัก', 'phàk', 'Vegetable'),
        ('ผลไม้', 'phǒn-lá-máai', 'Fruit'),
        ('มะม่วง', 'má-mûang', 'Mango'),
        ('กล้วย', 'glûai', 'Banana'),
        ('ก๋วยเตี๋ยว', 'gǔai-dtǐao', 'Noodle soup'),
        ('ข้าวผัด', 'khâao-phàt', 'Fried rice'),
        ('ส้มตำ', 'sôm-dtam', 'Papaya salad'),
        ('นม', 'nom', 'Milk'),
        ('น้ำแข็ง', 'náam-khǎeng', 'Ice'),
        ('เบียร์', 'bia', 'Beer'),
        ('หวาน', 'wǎan', 'Sweet'),
        ('เค็ม', 'khem', 'Salty'),
        ('เปรี้ยว', 'bprîao', 'Sour'),
        ('ขม', 'khǒm', 'Bitter'),
        ('จาน', 'jaan', 'Plate'),
        ('ช้อน', 'cháwn', 'Spoon'),
        ('ส้อม', 'sâwm', 'Fork'),
        ('แก้ว', 'gâew', 'Glass (for drinking)'),
        # time
        ('เวลา', 'wee-laa', 'Time'),
        ('วัน', 'wan', 'Day'),
        ('สัปดาห์', 'sàp-daa', 'Week'),
        ('เดือน', 'duean', 'Month'),
        ('ปี', 'bpii', 'Year'),
        ('ชั่วโมง', 'chûa-moong', 'Hour'),
        ('นาที', 'naa-thii', 'Minute'),
        ('เช้า', 'cháao', 'Morning'),
        ('เที่ยง', 'thîang', 'Noon'),
        ('บ่าย', 'bàai', 'Afternoon'),
        ('เย็น', 'yen', 'Evening / Cool'),
        ('กลางคืน', 'glaang-khuen', 'Night'),
        ('วันจันทร์', 'wan jan', 'Monday'),
        ('วันอังคาร', 'wan ang-khaan', 'Tuesday'),
        ('วันพุธ', 'wan phút', 'Wednesday'),
        ('วันพฤหัสบดี', 'wan phá-rúe-hàt-sà-baw-dii', 'Thursday'),
        ('วันศุกร์', 'wan sùk', 'Friday'),
        ('วันเสาร์', 'wan sǎo', 'Saturday'),
        ('วันอาทิตย์', 'wan aa-thít', 'Sunday'),
        ('เร็ว', 'reo', 'Fast / Early'),
        ('ช้า', 'cháa', 'Slow / Late'),
        # places & getting around
        ('โรงเรียน', 'roong-rian', 'School'),
        ('โรงพยาบาล', 'roong-phá-yaa-baan', 'Hospital'),
        ('สนามบิน', 'sà-nǎam-bin', 'Airport'),
        ('สถานี', 'sà-thǎa-nii', 'Station'),
        ('วัด', 'wát', 'Temple'),
        ('ทะเล', 'thá-lee', 'Sea'),
        ('ภูเขา', 'phuu-khǎo', 'Mountain'),
        ('ถนน', 'thà-nǒn', 'Road / Street'),
        ('รถ', 'rót', 'Car / Vehicle'),
        ('รถไฟ', 'rót-fai', 'Train'),
        ('รถเมล์', 'rót-mee', 'Bus'),
        ('เครื่องบิน', 'khrûeang-bin', 'Airplane'),
        ('เรือ', 'ruea', 'Boat'),
        ('ตั๋ว', 'dtǔa', 'Ticket'),
        ('ซ้าย', 'sáai', 'Left'),
        ('ขวา', 'khwǎa', 'Right'),
        ('ตรงไป', 'dtrong bpai', 'Go straight'),
        ('ใกล้', 'glâi', 'Near'),
        ('ไกล', 'glai', 'Far'),
        # body
        ('หัว', 'hǔa', 'Head'),
        ('หู', 'hǔu', 'Ear'),
        ('จมูก', 'jà-mùuk', 'Nose'),
        ('ปาก', 'bpàak', 'Mouth'),
        ('ฟัน', 'fan', 'Tooth / Teeth'),
        ('มือ', 'mue', 'Hand'),
        ('ขา', 'khǎa', 'Leg'),
        ('เท้า', 'tháao', 'Foot'),
        ('ท้อง', 'tháwng', 'Stomach / Belly'),
        ('หัวใจ', 'hǔa-jai', 'Heart'),
        # colors & weather
        ('สี', 'sǐi', 'Color'),
        ('สีแดง', 'sǐi daeng', 'Red'),
        ('สีเขียว', 'sǐi khǐao', 'Green'),
        ('สีฟ้า', 'sǐi fáa', 'Light blue / Sky blue'),
        ('สีน้ำเงิน', 'sǐi náam-ngern', 'Dark blue'),
        ('สีเหลือง', 'sǐi lǔeang', 'Yellow'),
        ('สีขาว', 'sǐi khǎao', 'White'),
        ('สีดำ', 'sǐi dam', 'Black'),
        ('สีชมพู', 'sǐi chom-phuu', 'Pink'),
        ('อากาศ', 'aa-gàat', 'Weather / Air'),
        ('ฝนตก', 'fǒn dtòk', "It's raining"),
        ('แดด', 'dàet', 'Sunshine'),
        ('ลม', 'lom', 'Wind'),
        # more verbs
        ('ตื่น', 'dtùen', 'To wake up'),
        ('อาบน้ำ', 'àap-náam', 'To shower / bathe'),
        ('เล่น', 'lên', 'To play'),
        ('ร้องเพลง', 'ráwng-phleeng', 'To sing'),
        ('เต้น', 'dtên', 'To dance'),
        ('ขับรถ', 'khàp rót', 'To drive'),
        ('จ่าย', 'jàai', 'To pay'),
        ('ถาม', 'thǎam', 'To ask'),
        ('ตอบ', 'dtàwp', 'To answer'),
        ('ช่วย', 'chûai', 'To help'),
        ('เปิด', 'bpèrt', 'To open / turn on'),
        ('ปิด', 'bpìt', 'To close / turn off'),
        ('ลืม', 'luem', 'To forget'),
        ('จำ', 'jam', 'To remember'),
        ('คิด', 'khít', 'To think'),
        ('คิดถึง', 'khít-thǔeng', 'To miss (someone)'),
        ('รู้สึก', 'rúu-sùek', 'To feel'),
        ('หา', 'hǎa', 'To look for'),
        ('เจอ', 'jer', 'To find / meet'),
        ('ใช้', 'chái', 'To use'),
        ('ส่ง', 'sòng', 'To send'),
        ('ทำอาหาร', 'tham aa-hǎan', 'To cook'),
        # feelings & descriptions
        ('ดีใจ', 'dii-jai', 'Glad / Happy'),
        ('เสียใจ', 'sǐa-jai', 'Sad / Sorry (regretful)'),
        ('โกรธ', 'gròot', 'Angry'),
        ('กลัว', 'glua', 'Afraid'),
        ('เบื่อ', 'bùea', 'Bored'),
        ('ตื่นเต้น', 'dtùen-dtên', 'Excited'),
        ('เหงา', 'ngǎo', 'Lonely'),
        ('ง่วง', 'ngûang', 'Sleepy'),
        ('ป่วย', 'bpùai', 'Sick'),
        ('เจ็บ', 'jèp', 'Hurt / Painful'),
        ('น่ารัก', 'nâa-rák', 'Cute / Lovely'),
        ('หล่อ', 'làw', 'Handsome'),
        ('สูง', 'sǔung', 'Tall / High'),
        ('เตี้ย', 'dtîa', 'Short (height)'),
        ('ยาว', 'yaao', 'Long'),
        ('สั้น', 'sân', 'Short (length)'),
        ('ง่าย', 'ngâai', 'Easy'),
        ('ยาก', 'yâak', 'Difficult'),
        ('สะอาด', 'sà-àat', 'Clean'),
        ('สกปรก', 'sòk-gà-bpròk', 'Dirty'),
        ('ว่าง', 'wâang', 'Free (not busy) / Empty'),
        ('ยุ่ง', 'yûng', 'Busy'),
    ]),

    ("intermediate", "Intermediate — connecting ideas", [
        # linking words
        ('และ', 'láe', 'And'),
        ('หรือ', 'rǔe', 'Or'),
        ('แต่', 'dtàe', 'But'),
        ('เพราะ', 'phráw', 'Because'),
        ('ถ้า', 'thâa', 'If'),
        ('ก็', 'gâw', 'Also / So / Then'),
        ('แล้ว', 'láew', 'Already / And then'),
        ('ยัง', 'yang', 'Still / Yet'),
        ('ยังไม่', 'yang mâi', 'Not yet'),
        ('เคย', 'khoei', 'Have ever (done)'),
        ('ไม่เคย', 'mâi khoei', 'Never (have done)'),
        ('จะ', 'jà', 'Will (future marker)'),
        ('กำลัง', 'gam-lang', 'In the middle of (doing)'),
        ('ต้อง', 'dtâwng', 'Must / Have to'),
        ('ควร', 'khuan', 'Should'),
        ('อาจจะ', 'àat-jà', 'Might / Maybe'),
        ('เกือบ', 'gùeap', 'Almost'),
        ('ทุก', 'thúk', 'Every'),
        ('บ่อย', 'bòi', 'Often'),
        ('บางที', 'baang-thii', 'Sometimes / Maybe'),
        ('เสมอ', 'sà-měr', 'Always'),
        ('ด้วย', 'dûai', 'Too / Also / With'),
        ('กับ', 'gàp', 'With / And'),
        ('ของ', 'khǎwng', 'Of / Belonging to / Thing'),
        ('สำหรับ', 'sǎm-ràp', 'For'),
        ('เกี่ยวกับ', 'gìao-gàp', 'About / Concerning'),
        ('ระหว่าง', 'rá-wàang', 'Between / During'),
        ('ก่อน', 'gàwn', 'Before / First'),
        ('หลังจาก', 'lǎng-jàak', 'After'),
        ('ตั้งแต่', 'dtâng-dtàe', 'Since / From'),
        ('จนถึง', 'jon-thǔeng', 'Until'),
        ('เพื่อ', 'phûea', 'In order to / For'),
        ('ดังนั้น', 'dang-nán', 'Therefore'),
        ('อย่างไรก็ตาม', 'yàang-rai gâw dtaam', 'However'),
        ('จริงๆ', 'jing-jing', 'Really / Truly'),
        ('เลย', 'loei', 'At all / Totally (emphasis)'),
        ('ค่อยๆ', 'khôi-khôi', 'Gradually / Gently'),
        ('ทันที', 'than-thii', 'Immediately'),
        ('เกินไป', 'gern bpai', 'Too (much)'),
        # sentence particles
        ('นะ', 'ná', 'Softening particle ("okay?", "you know")'),
        ('สิ', 'sì', 'Urging particle ("go on!", "of course")'),
        ('ล่ะ', 'lâ', 'Particle: "And what about …?"'),
        ('เหรอ', 'rěr', 'Particle: "Really?" (checking)'),
        ('หรอก', 'ràwk', 'Particle that softens a denial ("not really")'),
        # classifiers
        ('ตัว', 'dtua', 'Classifier: animals, clothes, chairs'),
        ('อัน', 'an', 'Classifier: small things in general'),
        ('ใบ', 'bai', 'Classifier: bags, cups, sheets, tickets'),
        ('เล่ม', 'lêm', 'Classifier: books, knives'),
        ('คัน', 'khan', 'Classifier: cars, umbrellas, spoons'),
        ('ขวด', 'khùat', 'Bottle / Classifier for bottles'),
        ('ชิ้น', 'chín', 'Piece / Classifier for pieces'),
        # abstract nouns
        ('ความรัก', 'khwaam-rák', 'Love (noun)'),
        ('ความฝัน', 'khwaam-fǎn', 'A dream'),
        ('ความคิด', 'khwaam-khít', 'An idea / A thought'),
        ('ความสุข', 'khwaam-sùk', 'Happiness'),
        ('ปัญหา', 'bpan-hǎa', 'Problem'),
        ('คำถาม', 'kham-thǎam', 'Question'),
        ('คำตอบ', 'kham-dtàwp', 'Answer'),
        ('ประสบการณ์', 'bprà-sòp-gaan', 'Experience'),
        ('โอกาส', 'oo-gàat', 'Opportunity / Chance'),
        ('อนาคต', 'à-naa-khót', 'Future'),
        ('อดีต', 'à-dìit', 'Past'),
        ('ปัจจุบัน', 'bpàt-jù-ban', 'Present / Nowadays'),
        ('ชีวิต', 'chii-wít', 'Life'),
        ('สุขภาพ', 'sùk-khà-phâap', 'Health'),
        ('ภาษา', 'phaa-sǎa', 'Language'),
        ('ประเทศ', 'bprà-thêet', 'Country'),
        ('เมือง', 'mueang', 'City / Town'),
        ('วัฒนธรรม', 'wát-thá-ná-tham', 'Culture'),
        ('ประวัติศาสตร์', 'bprà-wàt-sàat', 'History'),
        ('ธรรมชาติ', 'tham-má-châat', 'Nature'),
        ('เพลง', 'phleeng', 'Song'),
        ('หนัง', 'nǎng', 'Movie / Leather'),
        ('หนังสือ', 'nǎng-sǔe', 'Book'),
        ('ข่าว', 'khàao', 'News'),
        # work & study
        ('งาน', 'ngaan', 'Work / Job / Event'),
        ('เงิน', 'ngern', 'Money / Silver'),
        ('เงินเดือน', 'ngern-duean', 'Salary'),
        ('บริษัท', 'baw-rí-sàt', 'Company'),
        ('ประชุม', 'bprà-chum', 'Meeting / To meet'),
        ('เจ้านาย', 'jâo-naai', 'Boss'),
        ('เพื่อนร่วมงาน', 'phûean-rûam-ngaan', 'Colleague'),
        ('ลูกค้า', 'lûuk-kháa', 'Customer'),
        ('นักเรียน', 'nák-rian', 'Student'),
        ('ครู', 'khruu', 'Teacher'),
        ('การบ้าน', 'gaan-bâan', 'Homework'),
        ('สอบ', 'sàwp', 'Exam / To take a test'),
        ('ฝึก', 'fùek', 'To practice / train'),
        ('พยายาม', 'phá-yaa-yaam', 'To try / make an effort'),
        ('ตัดสินใจ', 'dtàt-sǐn-jai', 'To decide'),
        ('เลือก', 'lûeak', 'To choose'),
        ('เปลี่ยน', 'bplìan', 'To change'),
        ('เตรียม', 'dtriam', 'To prepare'),
        ('อธิบาย', 'à-thí-baai', 'To explain'),
        ('แนะนำ', 'náe-nam', 'To recommend / introduce'),
        ('สัญญา', 'sǎn-yaa', 'To promise / A contract'),
        ('เชื่อ', 'chûea', 'To believe'),
        ('หวัง', 'wǎng', 'To hope'),
        ('สงสัย', 'sǒng-sǎi', 'To wonder / doubt'),
        # character & feelings
        ('เกรงใจ', 'greeng-jai', 'Not wanting to impose on others'),
        ('ใจดี', 'jai-dii', 'Kind'),
        ('ใจเย็น', 'jai-yen', 'Calm / Patient'),
        ('ขี้เกียจ', 'khîi-gìat', 'Lazy'),
        ('ขยัน', 'khà-yǎn', 'Hardworking'),
        ('สำคัญ', 'sǎm-khan', 'Important'),
        ('จำเป็น', 'jam-bpen', 'Necessary'),
        ('เป็นห่วง', 'bpen-hùang', 'To worry about (someone)'),
        ('อิจฉา', 'ìt-chǎa', 'Jealous'),
        ('ภูมิใจ', 'phuum-jai', 'Proud'),
        ('ประหลาดใจ', 'bprà-làat-jai', 'Surprised'),
        ('ผิดหวัง', 'phìt-wǎng', 'Disappointed'),
        ('เข้าใจผิด', 'khâo-jai phìt', 'To misunderstand'),
        # handy expressions
        ('สู้ๆ', 'sûu-sûu', 'You can do it! / Fighting!'),
        ('ตามสบาย', 'dtaam sà-baai', 'Make yourself comfortable'),
        ('เดี๋ยวก่อน', 'dǐao gàwn', 'Wait a moment'),
        ('จริงเหรอ', 'jing rěr', 'Really?'),
        ('แน่นอน', 'nâe-nawn', 'Certainly / Of course'),
        ('ไม่ต้องห่วง', 'mâi dtâwng hùang', "Don't worry"),
        ('เป็นยังไงบ้าง', 'bpen yang-ngai bâang', "How's it going?"),
        ('ไปเที่ยว', 'bpai thîao', 'To go out / travel for fun'),
        ('เหมือนกัน', 'mǔean-gan', 'Same here / Likewise'),
    ]),

    ("advanced", "Advanced — news & formal Thai", [
        # government & society
        ('รัฐบาล', 'rát-thà-baan', 'Government'),
        ('นายกรัฐมนตรี', 'naa-yók rát-thà-mon-dtrii', 'Prime minister'),
        ('การเมือง', 'gaan-mueang', 'Politics'),
        ('เศรษฐกิจ', 'sèet-thà-gìt', 'Economy'),
        ('สังคม', 'sǎng-khom', 'Society'),
        ('การศึกษา', 'gaan-sùek-sǎa', 'Education'),
        ('สิ่งแวดล้อม', 'sìng-wâet-láwm', 'Environment'),
        ('เทคโนโลยี', 'théek-noo-loo-yii', 'Technology'),
        ('วิทยาศาสตร์', 'wít-thá-yaa-sàat', 'Science'),
        ('การพัฒนา', 'gaan-phát-thá-naa', 'Development'),
        ('นโยบาย', 'ná-yoo-baai', 'Policy'),
        ('กฎหมาย', 'gòt-mǎai', 'Law'),
        ('ประชาธิปไตย', 'bprà-chaa-thíp-bpà-dtai', 'Democracy'),
        ('การเลือกตั้ง', 'gaan-lûeak-dtâng', 'Election'),
        ('ประชาชน', 'bprà-chaa-chon', 'The public / Citizens'),
        ('รัฐธรรมนูญ', 'rát-thà-tham-má-nuun', 'Constitution'),
        ('เจ้าหน้าที่', 'jâo-nâa-thîi', 'Official / Staff member'),
        ('องค์กร', 'ong-gawn', 'Organization'),
        ('สถาบัน', 'sà-thǎa-ban', 'Institution'),
        ('มหาวิทยาลัย', 'má-hǎa-wít-thá-yaa-lai', 'University'),
        ('งานวิจัย', 'ngaan wí-jai', 'Research'),
        ('สถิติ', 'sà-thì-dtì', 'Statistics'),
        ('ข้อมูล', 'khâw-muun', 'Data / Information'),
        ('ประชากร', 'bprà-chaa-gawn', 'Population'),
        # cause, effect & analysis
        ('ผลกระทบ', 'phǒn-grà-thóp', 'Impact / Effect'),
        ('สาเหตุ', 'sǎa-hèet', 'Cause'),
        ('ผลลัพธ์', 'phǒn-láp', 'Result / Outcome'),
        ('แนวโน้ม', 'naew-nóom', 'Trend / Tendency'),
        ('วิกฤต', 'wí-grìt', 'Crisis'),
        ('สถานการณ์', 'sà-thǎa-ná-gaan', 'Situation'),
        ('ความร่วมมือ', 'khwaam-rûam-mue', 'Cooperation'),
        ('ความรับผิดชอบ', 'khwaam-ráp-phìt-châwp', 'Responsibility'),
        ('ความปลอดภัย', 'khwaam-bplàwt-phai', 'Safety / Security'),
        ('ความเท่าเทียม', 'khwaam-thâo-thiam', 'Equality'),
        ('เสรีภาพ', 'sěe-rii-phâap', 'Freedom / Liberty'),
        ('สิทธิ', 'sìt', 'Rights'),
        ('หน้าที่', 'nâa-thîi', 'Duty'),
        ('ผู้เชี่ยวชาญ', 'phûu-chîao-chaan', 'Expert'),
        ('ความคิดเห็น', 'khwaam-khít-hěn', 'Opinion'),
        ('ข้อเสนอ', 'khâw-sà-něr', 'Proposal'),
        ('ข้อตกลง', 'khâw-dtòk-long', 'Agreement'),
        ('ระดับ', 'rá-dàp', 'Level'),
        # economy & business
        ('ประสิทธิภาพ', 'bprà-sìt-thí-phâap', 'Efficiency'),
        ('คุณภาพ', 'khun-ná-phâap', 'Quality'),
        ('ปริมาณ', 'bpà-rí-maan', 'Quantity'),
        ('มาตรฐาน', 'mâat-dtrà-thǎan', 'Standard'),
        ('งบประมาณ', 'ngóp-bprà-maan', 'Budget'),
        ('การลงทุน', 'gaan-long-thun', 'Investment'),
        ('ภาษี', 'phaa-sǐi', 'Tax'),
        ('เงินเฟ้อ', 'ngern-fér', 'Inflation'),
        ('การส่งออก', 'gaan-sòng-àwk', 'Export'),
        ('การนำเข้า', 'gaan-nam-khâo', 'Import'),
        ('อุตสาหกรรม', 'ùt-sǎa-hà-gam', 'Industry'),
        ('เกษตรกรรม', 'gà-sèet-dtrà-gam', 'Agriculture'),
        ('การท่องเที่ยว', 'gaan-thâwng-thîao', 'Tourism'),
        ('โครงการ', 'khroong-gaan', 'Project'),
        ('กลยุทธ์', 'gon-lá-yút', 'Strategy'),
        ('เป้าหมาย', 'bpâo-mǎai', 'Goal / Target'),
        ('วิสัยทัศน์', 'wí-sǎi-thát', 'Vision'),
        # formal verbs
        ('ประเมิน', 'bprà-mern', 'To evaluate / assess'),
        ('วิเคราะห์', 'wí-khráw', 'To analyze'),
        ('สนับสนุน', 'sà-nàp-sà-nǔn', 'To support'),
        ('คัดค้าน', 'khát-kháan', 'To oppose / object'),
        ('เจรจา', 'jee-rá-jaa', 'To negotiate'),
        ('ประกาศ', 'bprà-gàat', 'To announce'),
        ('อนุมัติ', 'à-nú-mát', 'To approve'),
        ('ดำเนินการ', 'dam-nern-gaan', 'To carry out / proceed'),
        ('ปฏิบัติ', 'bpà-dtì-bàt', 'To practice / perform (duties)'),
        ('ส่งเสริม', 'sòng-sěrm', 'To promote / encourage'),
        ('ป้องกัน', 'bpâwng-gan', 'To prevent / protect'),
        ('แก้ไข', 'gâe-khǎi', 'To fix / resolve'),
        ('ยกเลิก', 'yók-lêrk', 'To cancel'),
        ('เผยแพร่', 'phǒei-phrâe', 'To publish / spread'),
        ('อ้างอิง', 'âang-ing', 'To cite / refer to'),
        ('เปรียบเทียบ', 'bprìap-thîap', 'To compare'),
        ('ตระหนัก', 'dtrà-nàk', 'To be aware / realize'),
        ('คำนึงถึง', 'kham-nueng-thǔeng', 'To take into account'),
        # formal descriptions
        ('ยั่งยืน', 'yâng-yuen', 'Sustainable'),
        ('ซับซ้อน', 'sáp-sáwn', 'Complex'),
        ('เหมาะสม', 'màw-sǒm', 'Appropriate / Suitable'),
        ('เป็นทางการ', 'bpen thaang-gaan', 'Formal / Official'),
        ('เกี่ยวข้อง', 'gìao-khâwng', 'Related / Involved'),
        ('ทั่วโลก', 'thûa-lôok', 'Worldwide'),
        # idioms
        ('น้ำขึ้นให้รีบตัก', 'náam khûen hâi rîip dtàk',
         'Idiom: make hay while the sun shines'),
        ('หมูไปไก่มา', 'mǔu bpai gài maa', 'Idiom: give and take'),
        ('ชาติหน้าตอนบ่ายๆ', 'châat-nâa dtawn bàai-bàai',
         'Idiom: when pigs fly (lit. "next life, in the afternoon")'),
        ('ไก่เห็นตีนงู งูเห็นนมไก่', 'gài hěn dtiin nguu, nguu hěn nom gài',
         "Idiom: two people who know each other's secrets"),
        ('เกลือเป็นหนอน', 'gluea bpen nǎwn', 'Idiom: a traitor within the group'),
        ('ปากหวาน', 'bpàak-wǎan', 'Sweet-talking'),
        ('ใจลอย', 'jai-loi', 'Absent-minded / Daydreaming'),
    ]),
]

LEVEL_KEYS = [key for key, _, _ in LEVELS]
LEVEL_NAMES = {key: name for key, name, _ in LEVELS}

# Every word, beginner -> advanced (kept for code that wants the full deck).
VOCAB = [w for _, _, words in LEVELS for w in words]


def deck(levels="all"):
    """Words for one level key, a list of keys, or "all".
    Higher levels never include the lower ones, so "Intermediate" on its
    own only shows intermediate words; pass several keys to mix."""
    if levels == "all":
        return list(VOCAB)
    if isinstance(levels, str):
        levels = [levels]
    return [w for key, _, words in LEVELS if key in levels for w in words]


class Shuffler:
    """Hands out words in a random order without repeats until the whole
    deck has been seen (a 'shuffle bag'), which is better for learning
    than pure random picks."""

    def __init__(self, words):
        self.words = list(words)
        self.bag = []

    def next(self):
        import random
        if not self.bag:
            self.bag = self.words[:]
            random.shuffle(self.bag)
        return self.bag.pop()
